
SLDefine = {}

------------------------------------------------------------------------------------------------------------------------
LUA_EVENT_SERVER_U_VALUE_UPDATE     = "LUA_EVENT_SERVER_U_VALUE_UPDATE"         -- 服务器变量改变
LUA_EVENT_SERVER_T_VALUE_UPDATE     = "LUA_EVENT_SERVER_T_VALUE_UPDATE"         -- 服务器变量改变
LUA_EVENT_SERVER_G_VALUE_UPDATE     = "LUA_EVENT_SERVER_G_VALUE_UPDATE"         -- 服务器变量改变
LUA_EVENT_SERVER_A_VALUE_UPDATE     = "LUA_EVENT_SERVER_A_VALUE_UPDATE"         -- 服务器变量改变

LUA_EVENT_ROLE_PROPERTY_INITED      = "LUA_EVENT_ROLE_PROPERTY_INITED"          -- 玩家角色属性初始化完毕
LUA_EVENT_ROLE_PROPERTY_CHANGE      = "LUA_EVENT_ROLE_PROPERTY_CHANGE"          -- 玩家属性变化时
LUA_EVENT_HERO_ROLE_PROPERTY_INITED = "LUA_EVENT_HERO_ROLE_PROPERTY_INITED"     -- 英雄角色属性初始化完毕


LUA_EVENT_LEVEL_CHANGE              = "LUA_EVENT_LEVEL_CHANGE"                 	-- 等级改变
LUA_EVENT_HERO_LEVEL_CHANGE         = "LUA_EVENT_HERO_LEVEL_CHANGE"            	-- 英雄等级改变
LUA_EVENT_REINLEVEL_CHANGE          = "LUA_EVENT_REINLEVEL_CHANGE"              -- 转生等级改变
LUA_EVENT_HERO_REINLEVEL_CHANGE     = "LUA_EVENT_HERO_REINLEVEL_CHANGE"         -- 英雄转生等级改变
LUA_EVENT_HPMP_CHANGE               = "LUA_EVENT_HPMP_CHANGE"                   -- HP/MP改变
LUA_EVENT_HERO_HPMP_CHANGE          = "LUA_EVENT_HERO_HPMP_CHANGE"              -- 英雄HP/MP改变
LUA_EVENT_EXP_CHANGE                = "LUA_EVENT_EXP_CHANGE"                    -- EXP改变
LUA_EVENT_HERO_EXP_CHANGE           = "LUA_EVENT_HERO_EXP_CHANGE"               -- 英雄EXP改变
LUA_EVENT_BATTERY_CHANGE            = "LUA_EVENT_BATTERY_CHANGE"                -- 电池电量改变
LUA_EVENT_NET_CHANGE                = "LUA_EVENT_NET_CHANGE"                    -- 网络状态改变
LUA_EVENT_WEIGHT_CHANGE             = "LUA_EVENT_WEIGHT_CHANGE"                 -- 负重改变

LUA_EVENT_PKMODE_CHANGE             = "LUA_EVENT_PKMODE_CHANGE"                 -- pk模式改变
LUA_EVENT_PKPOINT_CHANGE			= "LUA_EVENT_PKPOINT_CHANGE"				-- pk点数改变
LUA_EVENT_CANREVIVE_STATUS_CHANGE	= "LUA_EVENT_CANREVIVE_STATUS_CHANGE"		-- 可复活状态改变

LUA_EVENT_THROW_DAMAGE				= "LUA_EVENT_THROW_DAMAGE"				    -- 飘血

LUA_EVENT_AFKBEGIN                  = "LUA_EVENT_AFKBEGIN"                      -- 自动挂机开始
LUA_EVENT_AFKEND                    = "LUA_EVENT_AFKEND"                        -- 自动挂机结束
LUA_EVENT_AUTOMOVEBEGIN             = "LUA_EVENT_AUTOMOVEBEGIN"                 -- 自动寻路开始
LUA_EVENT_AUTOMOVEEND               = "LUA_EVENT_AUTOMOVEEND"                   -- 自动寻路结束
LUA_EVENT_AUTOPICKBEGIN             = "LUA_EVENT_AUTOPICKBEGIN"                 -- 自动捡物开始
LUA_EVENT_AUTOPICKEND               = "LUA_EVENT_AUTOPICKEND"                   -- 自动捡物结束

LUA_EVENT_MAIN_PICKUP_SHOW			= "LUA_EVENT_MAIN_PICKUP_SHOW"				-- 拾取按钮是否显示

LUA_EVENT_MAINPLAYER_BUFF_UPDATE    = "LUA_EVENT_MAINPLAYER_BUFF_UPDATE"     	-- 主玩家buff刷新
LUA_EVENT_BUFF_UPDATE              	= "LUA_EVENT_BUFF_UPDATE"                	-- 通用buff刷新
LUA_EVENT_ACTOR_ENTER_BUFF			= "LUA_EVENT_ACTOR_ENTER_BUFF"				-- 玩家进入某BUFF
LUA_EVENT_ACTOR_EXIT_BUFF			= "LUA_EVENT_ACTOR_EXIT_BUFF"				-- 玩家退出某BUFF
LUA_EVENT_ACTOR_UPDATE_BUFF_PRESENT = "LUA_EVENT_ACTOR_UPDATE_BUFF_PRESENT"		-- 玩家更新某BUFF表现


LUA_EVENT_TALKTONPC                 = "LUA_EVENT_TALKTONPC"                     -- 与NPC对话

LUA_EVENT_CHANGESCENE               = "LUA_EVENT_CHANGESCENE"                   -- 切换地图(包含同地图)
LUA_EVENT_MAP_INFO_CHANGE           = "LUA_EVENT_MAP_INFO_CHANGE"              	-- 切换地图(不同地图)
LUA_EVENT_MAP_INFO_INIT            	= "LUA_EVENT_MAP_INFO_INIT"                	-- 初始化地图
LUA_EVENT_MAP_STATE_CHANGE          = "LUA_EVENT_MAP_STATE_CHANGE"              -- 地图状态改变
LUA_EVENT_MAP_SIEGEAREA_CHANGE      = "LUA_EVENT_MAP_SIEGEAREA_CHANGE"          -- 是否进入攻城区域状态改变

LUA_EVENT_OPENWIN					= "LUA_EVENT_OPENWIN"						-- 打开界面
LUA_EVENT_CLOSEWIN                  = "LUA_EVENT_CLOSEWIN"                      -- 关闭界面

LUA_EVENT_WINDOW_CHANGE             = "LUA_EVENT_WINDOW_CHANGE"                 -- 窗体尺寸改变时
LUA_EVENT_DEVICE_ROTATION_CHANGED   = "LUA_EVENT_DEVICE_ROTATION_CHANGED"       -- 设备方向改变

LUA_EVENT_MONEY_CHANGE               = "LUA_EVENT_MONEY_CHANGE"                   -- 货币变化时

LUA_EVENT_GUILD_JOIN_STATE_CHANGE	= "LUA_EVENT_GUILD_JOIN_STATE_CHANGE"		-- 加入行会状态改变
LUA_EVENT_GUILD_MAIN_INFO           = "LUA_EVENT_GUILD_MAIN_INFO"               -- 行会信息
LUA_EVENT_GUILD_MEMBER_LIST			= "LUA_EVENT_GUILD_MEMBER_LIST"				-- 行会成员列表
LUA_EVENT_GUILD_WORLDLIST           = "LUA_EVENT_GUILD_WORLDLIST"               -- 世界行会列表
LUA_EVENT_GUILD_CHILD_REMOVE		= "LUA_EVENT_GUILD_CHILD_REMOVE"			-- 行会子界面移除
LUA_EVENT_GUILD_CREATE_SUCCESS      = "LUA_EVENT_GUILD_CREATE_SUCCESS"          -- 行会创建成功
LUA_EVENT_GUILD_JOIN_SUCCESS		= "LUA_EVENT_GUILD_JOIN_SUCCESS"			-- 加入行会成功
LUA_EVENT_GUILD_APPLYLIST           = "LUA_EVENT_GUILD_APPLYLIST"               -- 入会申请列表
LUA_EVENT_GUILD_APPLY_ALLY_LIST 	= "LUA_EVENT_GUILD_APPLY_ALLY_LIST"     	-- 申请结盟列表
LUA_EVENT_GUILD_NOTICE_UPDATE		= "LUA_EVENT_GUILD_NOTICE_UPDATE"			-- 行会公告更新
LUA_EVENT_GUILD_ALLY_WAR_LIST		= "LUA_EVENT_GUILD_ALLY_WAR_LIST"			-- 联盟战争列表刷新
LUA_EVENT_GUILD_ALL_WAR_UPDATE		= "LUA_EVENT_GUILD_ALL_WAR_UPDATE"			-- 单行会联盟战争数据刷新
LUA_EVENT_GUILD_OPERATE_ERROR		= "LUA_EVENT_GUILD_OPERATE_ERROR"			-- 行会操作提示
LUA_EVENT_GUILD_SUB_MEMBER_SUCCESS  = "LUA_EVENT_GUILD_SUB_MEMBER_SUCCESS"		-- 行会删除成员成功
LUA_EVENT_GUILD_APPOINT_RANK_SUCCESS= "LUA_EVENT_GUILD_APPOINT_RANK_SUCCESS"	-- 任命成员职位成功
LUA_EVENT_GUILD_KICK_OUT			= "LUA_EVENT_GUILD_KICK_OUT"				-- 被踢出行会
LUA_EVENT_GUILD_QUIT_SUCCESS		= "LUA_EVENT_GUILD_QUIT_SUCCESS"			-- 退出行会成功
LUA_EVENT_GUILD_DISSOLVE			= "LUA_EVENT_GUILD_DISSOLVE"				-- 行会解散
LUA_EVENT_GUILD_AUTO_JOIN_STATE		= "LUA_EVENT_GUILD_AUTO_JOIN_STATE"			-- 行会自动加入状态
LUA_EVENT_GUILD_MEMBER_APPLY		= "LUA_EVENT_GUILD_MEMBER_APPLY"			-- 收到申请加入行会申请
LUA_EVENT_GUILD_ALLY_APPLY			= "LUA_EVENT_GUILD_ALLY_APPLY"				-- 收到行会联盟申请
LUA_EVENT_GUILD_JOIN_INVITE			= "LUA_EVENT_GUILD_JOIN_INVITE"				-- 收到行会加入邀请
LUA_EVENT_GUILD_PERMISSION			= "LUA_EVENT_GUILD_PERMISSION"				-- 行会管理状态改变

LUA_EVENT_TRADE_REQUEST_ERROR_TIPS  = "LUA_EVENT_TRADE_REQUEST_ERROR_TIPS"      -- xx请求和你交易错误弹窗
LUA_EVENT_TRADE_FAIL_ERROR_TIPS     = "LUA_EVENT_TRADE_FAIL_ERROR_TIPS"        	-- 交易失败错误弹窗
LUA_EVENT_TRADE_CANCELED    		= "LUA_EVENT_TRADE_CANCELED"        	    -- 交易 被取消
LUA_EVENT_TRADE_TARGET_MONEY_CHANGE = "LUA_EVENT_TRADE_TARGET_MONEY_CHANGE" 	-- 对方交易货币改变
LUA_EVENT_TRADE_MYSELF_MONEY_CHANGE = "LUA_EVENT_TRADE_MYSELF_MONEY_CHANGE"     -- 自己交易货币改变
LUA_EVENT_TRADE_STATUS_CHANGE       = "LUA_EVENT_TRADE_STATUS_CHANGE"           -- 对方交易状态改变
LUA_EVENT_TRADE_MY_STATUS_CHANGE    = "LUA_EVENT_TRADE_MY_STATUS_CHANGE"        -- 自己交易状态改变
LUA_EVENT_TRADE_TRADER_ITEM_CHANGE  = "LUA_EVENT_TRADE_TRADER_ITEM_CHANGE"      -- 对方放入和取出物品消息  
LUA_EVENT_TRADE_MYSELF_ITEM_CHANGE  = "LUA_EVENT_TRADE_MYSELF_ITEM_CHANGE"      -- 自己放入和取出物品结果  
LUA_EVENT_TRADE_UNLOCK_OPERATION    = "LUA_EVENT_TRADE_UNLOCK_OPERATION"        --请解锁后再操作
LUA_EVENT_TRADE_STALL_FORBID        = "LUA_EVENT_TRADE_STALL_FORBID"            --摆摊中禁止操作
LUA_EVENT_TRADE_TARGET_MONEY_CHANGE_AUDIO = "LUA_EVENT_TRADE_TARGET_MONEY_CHANGE_AUDIO" --交易对方金币改变播放音效
--气泡
LUA_EVENT_TRADE_BUBBLE_TIPS_CHANGE  = "LUA_EVENT_TRADE_BUBBLE_TIPS_CHANGE"		--交易气泡提醒
LUA_EVENT_MAIL_BUBBLE_TIPS_CHANGE	= "LUA_EVENT_MAIL_BUBBLE_TIPS_CHANGE"		-- 邮件气泡提醒

LUA_EVENT_FIRE_WORK_HALL_SHOW		= "LUA_EVENT_FIRE_WORK_HALL_SHOW"            -- 烟花特效

-- 进入游戏公告
LUA_EVENT_GAME_WORLD_CONFIRM_UPDATE = "LUA_EVENT_GAME_WORLD_CONFIRM_UPDATE"		--更新世界公告内容

--背包里开宝箱
LUA_EVENT_GOLD_BOX_OPEN_ANIM    	= "LUA_EVENT_GOLD_BOX_OPEN_ANIM"			--开宝箱动画
LUA_EVENT_GOLD_BOX_REFRESH    	    = "LUA_EVENT_GOLD_BOX_REFRESH"				--刷新宝箱

LUA_EVENT_TREASUREBOX_DATA_REFRESH	= "LUA_EVENT_TREASUREBOX_DATA_REFRESH"		-- 宝箱数据刷新	

LUA_EVENT_SIGHT_BEAD_HIDE			= "LUA_EVENT_SIGHT_BEAD_HIDE" 				-- 隐藏准星 
LUA_EVENT_SIGHT_BEAD_SHOW 			= "LUA_EVENT_SIGHT_BEAD_SHOW"				-- 显示准星

LUA_EVENT_LAYER_MOVED_BEGIN			= "LUA_EVENT_LAYER_MOVED_BEGIN"				-- 开始拖动
LUA_EVENT_LAYER_MOVED_MOVING		= "LUA_EVENT_LAYER_MOVED_MOVING"			-- 更新拖动
LUA_EVENT_LAYER_MOVED_END			= "LUA_EVENT_LAYER_MOVED_END"				-- 结束拖动
LUA_EVENT_LAYER_MOVED_CANCEL		= "LUA_EVENT_LAYER_MOVED_CANCEL"			-- 取消拖动
LUA_EVENT_LAYER_MOVED_UP_DATA		= "LUA_EVENT_LAYER_MOVED_UP_DATA"			-- 更新部分数据

LUA_EVENT_RTOUCH_STATE_CHANGE		= "LUA_EVENT_RTOUCH_STATE_CHANGE"

LUA_EVENT_BAG_ITEM_MOVE_CANCEL		= "LUA_EVENT_BAG_ITEM_MOVE_CANCEL"			-- 背包道具移动取消
LUA_EVENT_BAG_ITEM_LIST_REFRESH    	= "LUA_EVENT_BAG_ITEM_LIST_REFRESH"         -- 刷新背包道具列表
LUA_EVENT_BAG_ITEM_CHANGE           = "LUA_EVENT_BAG_ITEM_CHANGE"               -- 背包数据发生变化时
LUA_EVENT_BAG_ITEM_POS_CHANGE       = "LUA_EVENT_BAG_ITEM_POS_CHANGE"           -- 背包道具位置发生变化时
LUA_EVENT_BAGLAYER_POS_CHANGE      	= "LUA_EVENT_BAGLAYER_POS_CHANGE"           -- 背包界面位置发生变化时
LUA_EVENT_BAG_STATE_CHANGE			= "LUA_EVENT_BAG_STATE_CHANGE"				-- 背包状态改变
LUA_EVENT_BAG_ITEM_COLLIMATOR		= "LUA_EVENT_BAG_ITEM_COLLIMATOR"			-- 道具开启准星
LUA_EVENT_BAG_ITEM_CHOOSE_STATE		= "LUA_EVENT_BAG_ITEM_CHOOSE_STATE"			-- 批量勾选背包物品

LUA_EVENT_HERO_BAG_ITEM_POS_CHANGE  = "LUA_EVENT_HERO_BAG_ITEM_POS_CHANGE"      -- 英雄背包道具位置发生变化时

LUA_EVENT_PLAYER_EQUIP_CHANGE       = "LUA_EVENT_PLAYER_EQUIP_CHANGE"           -- 角色装备数据操作
LUA_EVENT_HERO_EQUIP_CHANGE         = "LUA_EVENT_HERO_EQUIP_CHANGE"             -- 英雄装备变化
LUA_EVENT_NPC_STORAGE_CLOSE	        = "LUA_EVENT_NPC_STORAGE_CLOSE"				-- npc仓库界面 关闭

LUA_EVENT_EQUIP_STATE_CHANGE        = "LUA_EVENT_EQUIP_STATE_CHANGE"            -- 装备状态改变
LUA_EVENT_HERO_STATE_CHANGE   		= "LUA_EVENT_HERO_STATE_CHANGE"       		-- 英雄装备状态改变

LUA_EVENT_PLAYER_EMBATTLE_CHANGE	= "LUA_EVENT_PLAYER_EMBATTLE_CHANGE"		-- 装备法阵
LUA_EVENT_HERO_EMBATTLE_CHANGE		= "LUA_EVENT_HERO_EMBATTLE_CHANGE"			-- 英雄装备法阵

LUA_EVENT_HERO_BAG_ITEM_LIST_REFRESH= "LUA_EVENT_HERO_BAG_ITEM_LIST_REFRESH"    -- 刷新英雄背包道具列表
LUA_EVENT_HERO_BAG_ITEM_CHANGE      = "LUA_EVENT_HERO_BAG_ITEM_CHANGE"			-- 英雄背包数据发生变化时
LUA_EVENT_HERO_BAG_STATE_CHANGE		= "LUA_EVENT_HERO_BAG_STATE_CHANGE"			-- 英雄背包状态改变
LUA_EVENT_ITEM_MOVE_BEGIN_HERO_BAG_POS_CHANGE = "LUA_EVENT_ITEM_MOVE_BEGIN_HERO_BAG_POS_CHANGE"


LUA_EVENT_DISCONNECT                = "LUA_EVENT_DISCONNECT"                    -- 断线
LUA_EVENT_RECONNECT                 = "LUA_EVENT_RECONNECT"                     -- 重连

LUA_EVENT_TAKE_ON_EQUIP             = "LUA_EVENT_TAKE_ON_EQUIP"                 -- 玩家穿戴装备
LUA_EVENT_TAKE_OFF_EQUIP            = "LUA_EVENT_TAKE_OFF_EQUIP"                -- 玩家脱掉装备

LUA_EVENT_HERO_TAKE_ON_EQUIP        = "LUA_EVENT_HERO_TAKE_ON_EQUIP"            -- 英雄穿戴装备
LUA_EVENT_HERO_TAKE_OFF_EQUIP       = "LUA_EVENT_HERO_TAKE_OFF_EQUIP"           -- 英雄脱掉装备

LUA_EVENT_SETTING_CHANGE            = "LUA_EVENT_SETTING_CHANGE"                -- 设置项发生变化

LUA_EVENT_ACTOR_IN_OF_VIEW          = "LUA_EVENT_ACTOR_IN_OF_VIEW"              -- 进视野
LUA_EVENT_ACTOR_OUT_OF_VIEW         = "LUA_EVENT_ACTOR_OUT_OF_VIEW"             -- 出视野

LUA_EVENT_DROPITEM_IN_OF_VIEW       = "LUA_EVENT_DROPITEM_IN_OF_VIEW"           -- 掉落物进视野
LUA_EVENT_DROPITEM_OUT_OF_VIEW      = "LUA_EVENT_DROPITEM_OUT_OF_VIEW"          -- 掉落物出视野

LUA_EVENT_TARGET_CHANGE             = "LUA_EVENT_TARGET_CHANGE"                 -- 目标发生变化
LUA_EVENT_TARGET_OWNER_CHANGE		= "LUA_EVENT_TARGET_OWNER_CHANGE"			-- 目标怪物归属玩家改变
LUA_EVENT_ACTOR_OWNER_CHANGE        = "LUA_EVENT_ACTOR_OWNER_CHANGE"            -- 归属变化
LUA_EVENT_ACTOR_HP_REFRESH			= "LUA_EVENT_ACTOR_HP_REFRESH"				-- HP变化

LUA_EVENT_HERO_ANGER_CHANGE         = "LUA_EVENT_HERO_ANGER_CHANGE"             -- 英雄怒气改变 

LUA_EVENT_PLAYER_ACTION_BEGIN       = "LUA_EVENT_PLAYER_ACTION_BEGIN"           -- 主玩家行为状态改变（站立、走、跑等） 
LUA_EVENT_PLAYER_ACTION_COMPLETE    = "LUA_EVENT_PLAYER_ACTION_COMPLETE"        -- 主玩家行为状态改变（站立、走、跑等） 
LUA_EVENT_NET_PLAYER_ACTION_BEGIN   = "LUA_EVENT_NET_PLAYER_ACTION_BEGIN"       -- 网络玩家行为状态改变（站立、走、跑等） 
LUA_EVENT_NET_PLAYER_ACTION_COMPLETE= "LUA_EVENT_NET_PLAYER_ACTION_COMPLETE"    -- 网络玩家行为状态改变（站立、走、跑等） 
LUA_EVENT_MONSTER_ACTION_BEGIN      = "LUA_EVENT_MONSTER_ACTION_BEGIN"          -- 怪物行为状态改变（站立、走、跑等） 
LUA_EVENT_MONSTER_ACTION_COMPLETE   = "LUA_EVENT_MONSTER_ACTION_COMPLETE"       -- 怪物行为状态改变（站立、走、跑等） 
LUA_EVENT_ACTOR_GMDATA_UPDATE       = "LUA_EVENT_ACTOR_GMDATA_UPDATE"           -- 玩家/怪物 GM数据改变

LUA_EVENT_SKILL_INIT                = "LUA_EVENT_SKILL_INIT"                    -- 初始化技能
LUA_EVENT_SKILL_ADD                 = "LUA_EVENT_SKILL_ADD"                     -- 获得技能
LUA_EVENT_SKILL_DEL                 = "LUA_EVENT_SKILL_DEL"                     -- 删除技能
LUA_EVENT_SKILL_UPDATE              = "LUA_EVENT_SKILL_UPDATE"                  -- 更新技能

LUA_EVENT_HERO_SKILL_ADD            = "LUA_EVENT_HERO_SKILL_ADD"                -- 英雄新增普通技能
LUA_EVENT_HERO_SKILL_DEL            = "LUA_EVENT_HERO_SKILL_DEL"                -- 英雄删除普通技能
LUA_EVENT_HERO_SKILL_UPDATE         = "LUA_EVENT_HERO_SKILL_UPDATE"             -- 英雄技能更新

LUA_EVENT_SUMMON_MODE_CHANGE        = "LUA_EVENT_SUMMON_MODE_CHANGE"            -- 召唤物 状态改变
LUA_EVENT_SUMMON_ALIVE_CHANGE       = "LUA_EVENT_SUMMON_ALIVE_CHANGE"           -- 召唤物 存活状态改变

LUA_EVENT_BUBBLETIPS_STATUS_CHANGE  = "LUA_EVENT_BUBBLETIPS_STATUS_CHANGE"      -- 气泡状态改变
LUA_EVENT_PLAY_MAGICBALL_EFFECT     = "LUA_EVENT_PLAY_MAGICBALL_EFFECT"         -- 脚本魔血球动画
LUA_EVENT_AUTOFIGHT_TIPS_SHOW       = "LUA_EVENT_AUTOFIGHT_TIPS_SHOW"           -- 自动战斗提示显示与否
LUA_EVENT_AUTOMOVE_TIPS_SHOW        = "LUA_EVENT_AUTOMOVE_TIPS_SHOW"            -- 自动寻路提示显示与否
LUA_EVENT_REIN_ATTR_CHANGE          = "LUA_EVENT_REIN_ATTR_CHANGE"              -- 转生点数据变化

LUA_EVENT_ASSIST_MISSION_SHOW		= "LUA_EVENT_ASSIST_MISSION_SHOW"			-- 主界面-任务内容显示与否
LUA_EVENT_ASSIST_HIDESTATUS_CHANGE  = "LUA_EVENT_ASSIST_HIDESTATUS_CHANGE"      -- 主界面-任务栏显示和收缩状态改变
LUA_EVENT_TASK_TO_TOP               = "LUA_EVENT_TASK_TO_TOP"                   -- 主界面-辅助-任务置顶
LUA_EVENT_TASK_ADD                  = "LUA_EVENT_TASK_ADD"                      -- 主界面-辅助-任务增加
LUA_EVENT_TASK_CHANGE     			= "LUA_EVENT_TASK_CHANGE"         			-- 主界面-辅助-任务改变
LUA_EVENT_TASK_DEL                  = "LUA_EVENT_TASK_DEL"                      -- 主界面-辅助-任务移除
LUA_EVENT_TEAM_MEMBER_UPDATE        = "LUA_EVENT_TEAM_MEMBER_UPDATE"            -- 主界面-辅助-队伍刷新
LUA_EVENT_TEAM_NEAR_UPDATE          = "LUA_EVENT_TEAM_NEAR_UPDATE"              -- 附近队伍刷新
LUA_EVENT_TEAM_APPLY_UPDATE         = "LUA_EVENT_TEAM_APPLY_UPDATE"             -- 申请入队列表刷新

LUA_EVENT_RANK_PLAYER_UPDATE        = "LUA_EVENT_RANK_PLAYER_UPDATE"            -- 排行榜个人数据刷新
LUA_EVENT_RANK_DATA_UPDATE          = "LUA_EVENT_RANK_DATA_UPDATE"              -- 排行榜分类数据刷新

LUA_EVENT_BIND_MAINPLAYER           = "LUA_EVENT_BIND_MAINPLAYER"               -- 绑定主玩家
LUA_EVENT_PLAYER_MAPPOS_CHANGE      = "LUA_EVENT_PLAYER_MAPPOS_CHANGE"          -- 主玩家位置改变

LUA_EVENT_FRIEND_LIST_UPDATE        = "LUA_EVENT_FRIEND_LIST_UPDATE"            -- 好友列表刷新
LUA_EVENT_FRIEND_APPLY              = "LUA_EVENT_FRIEND_APPLY"                  -- 好友申请
LUA_EVENT_BLACK_LIST_UPDATE			= "LUA_EVENT_BLACK_LIST_UPDATE"				-- 黑名单列表刷新

-- 邮件
LUA_EVENT_MAIL_LIST_REFRESH         = "LUA_EVENT_MAIL_LIST_REFRESH"            	-- 邮件列表返回
LUA_EVENT_MAIL_DELETE_ALL_READ      = "LUA_EVENT_MAIL_DELETE_ALL_READ"          -- 邮件列表删除已读
LUA_EVENT_MAIL_UPDATE_ALL           = "LUA_EVENT_MAIL_UPDATE_ALL"               -- 邮件列表刷新
LUA_EVENT_MAIL_UPDATE               = "LUA_EVENT_MAIL_UPDATE"                   -- 邮件列表刷新
LUA_EVENT_MAIL_DELETE               = "LUA_EVENT_MAIL_DELETE"                   -- 邮件删除
LUA_EVENT_MAIL_NEW_NOTICE           = "LUA_EVENT_MAIL_NEW_NOTICE"               -- 邮件获得新邮件

LUA_EVENT_ITEMTIPS_MOUSE_SCROLL     = "LUA_EVENT_ITEMTIPS_MOUSE_SCROLL"         -- ITEMTIPS鼠标滚轮滚动

LUA_EVENT_MAIN_MINIMAP_SHOW_STATUS	= "LUA_EVENT_MAIN_MINIMAP_SHOW_STATUS"		-- 小地图显示状态改变
LUA_EVENT_PCMINIMAP_STATUS_CHANGE	= "LUA_EVENT_PCMINIMAP_STATUS_CHANGE"		-- PC主界面小地图展示状态改变
LUA_EVENT_MINIMAP_DOWNLOAD_SUCCESS  = "LUA_EVENT_MINIMAP_DOWNLOAD_SUCCESS"		-- 小地图下载成功
LUA_EVENT_MAPDATA_LOAD_SUCCESS		= "LUA_EVENT_MAPDATA_LOAD_SUCCESS"			-- 地图数据加载成功

LUA_EVENT_MAIN_PLAYER_REVIVE        = "LUA_EVENT_MAIN_PLAYER_REVIVE"            -- 主玩家复活            
LUA_EVENT_NET_PLAYER_REVIVE         = "LUA_EVENT_NET_PLAYER_REVIVE"             -- 网络玩家复活
LUA_EVENT_MONSTER_REVIVE            = "LUA_EVENT_MONSTER_REVIVE"                -- 怪物复活
LUA_EVENT_MONSTER_BIRTH             = "LUA_EVENT_MONSTER_BIRTH"                 -- 怪物出生

LUA_EVENT_MAIN_PLAYER_DIE           = "LUA_EVENT_MAIN_PLAYER_DIE"               -- 主玩家死亡
LUA_EVENT_NET_PLAYER_DIE            = "LUA_EVENT_NET_PLAYER_DIE"                -- 网络玩家死亡
LUA_EVENT_MONSTER_DIE               = "LUA_EVENT_MONSTER_DIE"                   -- 怪物死亡
LUA_EVENT_MONSTER_CAVED				= "LUA_EVENT_MONSTER_CAVED"					-- 钻地下

LUA_EVENT_ACTOR_DIE					= "LUA_EVENT_ACTOR_DIE"						-- 死亡（包含所有actor）
LUA_EVENT_ACTOR_REVIVE				= "LUA_EVENT_ACTOR_REVIVE"					-- 死亡（包含所有actor）

LUA_EVENT_NPCLAYER_OPENSTATUS       = "LUA_EVENT_NPCLAYER_OPENSTATUS"           -- NPC界面打开或关闭
LUA_EVENT_NPC_TALK                  = "LUA_EVENT_NPC_TALK"                      -- NPC 说话 (打开NPC界面)
LUA_EVENT_NPC_TALK_CLOSE            = "LUA_EVENT_NPC_TALK_CLOSE"                -- NPC 界面关闭
LUA_EVENT_NPC_STORE_ITEM_REMOVE     = "LUA_EVENT_NPC_STORE_ITEM_REMOVE"         -- NPC 商城移除item
LUA_EVENT_NPC_SELL_REPAIRE_UPDATE   = "LUA_EVENT_NPC_SELL_REPAIRE_UPDATE"       -- NPC 更新出售修理界面
LUA_EVENT_NPC_MAKE_DRUG_SUCCESS     = "LUA_EVENT_NPC_MAKE_DRUG_SUCCESS"         -- NPC 药品研制成功
LUA_EVENT_NPC_MAKE_DRUG_FAILED      = "LUA_EVENT_NPC_MAKE_DRUG_FAILED"          -- NPC 药品研制失败
LUA_EVENT_NPC_STORE_BUY_RESULT_FAIL = "LUA_EVENT_NPC_STORE_BUY_RESULT_FAIL"     -- NPC 商店购买失败
LUA_EVENT_NPC_SELL_OPEN             = "LUA_EVENT_NPC_SELL_OPEN"                 -- NPC 出售界面开启
LUA_EVENT_NPC_MAKE_DRUG_OPEN        = "LUA_EVENT_NPC_MAKE_DRUG_OPEN"            -- NPC 炼药界面开启
LUA_EVENT_NPC_STORE_OPEN            = "LUA_EVENT_NPC_STORE_OPEN"                -- NPC 商店界面开启

LUA_EVENT_OPEN_PROGRESSBAR        	= "LUA_EVENT_OPEN_PROGRESSBAR"             	-- 收到打开进度条消息

LUA_EVENT_BESTRONG_BUTTON_REFRESH   = "LUA_EVENT_BESTRONG_BUTTON_REFRESH"      	-- 变强按钮刷新
LUA_EVENT_BESTRONG_LIST_REFRESH     = "LUA_EVENT_BESTRONG_LIST_REFRESH"         -- 变强列表刷新
LUA_EVENT_BESTRONG_CLOSE     		= "LUA_EVENT_BESTRONG_CLOSE"          		-- 变强关闭

-- 人物内功
LUA_EVENT_PLAYER_INTERNAL_FORCE_CHANGE  = "LUA_EVENT_PLAYER_INTERNAL_FORCE_CHANGE"  -- 内力值改变
LUA_EVENT_PLAYER_INTERNAL_EXP_CHANGE    = "LUA_EVENT_PLAYER_INTERNAL_EXP_CHANGE"    -- 内功经验值改变
LUA_EVENT_PLAYER_INTERNAL_LEVEL_CHANGE  = "LUA_EVENT_PLAYER_INTERNAL_LEVEL_CHANGE"  -- 内功等级改变
LUA_EVENT_INTERNAL_SKILL_ADD            = "LUA_EVENT_INTERNAL_SKILL_ADD"            -- 内功技能增加
LUA_EVENT_INTERNAL_SKILL_DEL            = "LUA_EVENT_INTERNAL_SKILL_DEL"            -- 内功技能删除
LUA_EVENT_INTERNAL_SKILL_UPDATE         = "LUA_EVENT_INTERNAL_SKILL_UPDATE"         -- 内功技能刷新
LUA_EVENT_PLAYER_LEARNED_INTERNAL       = "LUA_EVENT_PLAYER_LEARNED_INTERNAL"       -- 人物学习内功

LUA_EVENT_MERIDIAN_DATA_REFRESH         = "LUA_EVENT_MERIDIAN_DATA_REFRESH"         -- 内功经络数据刷新
LUA_EVENT_PLAYER_INTERNAL_DZVALUE_CHANGE= "LUA_EVENT_PLAYER_INTERNAL_DZVALUE_CHANGE"-- 内功斗转值改变/恢复

LUA_EVENT_PLAYER_COMBO_SKILL_ADD        = "LUA_EVENT_PLAYER_COMBO_SKILL_ADD"        -- 人物连击技能增加
LUA_EVENT_PLAYER_COMBO_SKILL_DEL        = "LUA_EVENT_PLAYER_COMBO_SKILL_DEL"        -- 人物连击技能删除
LUA_EVENT_PLAYER_COMBO_SKILL_UPDATE     = "LUA_EVENT_PLAYER_COMBO_SKILL_UPDATE"     -- 人物连击技能刷新
LUA_EVENT_PLAYER_SET_COMBO_REFRESH      = "LUA_EVENT_PLAYER_SET_COMBO_REFRESH"      -- 人物设置连击技能刷新
LUA_EVENT_PLAYER_COMBO_SKILLCD_STATE    = "LUA_EVENT_PLAYER_COMBO_SKILLCD_STATE"    -- 人物连击技能CD状态
LUA_EVENT_PLAYER_OPEN_COMBO_NUM         = "LUA_EVENT_PLAYER_OPEN_COMBO_NUM"         -- 人物开启连击个数

-- 英雄内功
LUA_EVENT_HERO_INTERNAL_FORCE_CHANGE    = "LUA_EVENT_HERO_INTERNAL_FORCE_CHANGE"    -- 内力值改变
LUA_EVENT_HERO_INTERNAL_EXP_CHANGE      = "LUA_EVENT_HERO_INTERNAL_EXP_CHANGE"      -- 内功经验值改变
LUA_EVENT_HERO_INTERNAL_LEVEL_CHANGE    = "LUA_EVENT_HERO_INTERNAL_LEVEL_CHANGE"    -- 内功等级改变
LUA_EVENT_HERO_INTERNAL_SKILL_ADD       = "LUA_EVENT_HERO_INTERNAL_SKILL_ADD"       -- 英雄内功技能增加
LUA_EVENT_HERO_INTERNAL_SKILL_DEL       = "LUA_EVENT_HERO_INTERNAL_SKILL_DEL"       -- 英雄内功技能删除
LUA_EVENT_HERO_INTERNAL_SKILL_UPDATE    = "LUA_EVENT_HERO_INTERNAL_SKILL_UPDATE"    -- 英雄内功技能刷新
LUA_EVENT_HERO_LEARNED_INTERNAL         = "LUA_EVENT_HERO_LEARNED_INTERNAL"         -- 英雄学习内功

LUA_EVENT_HERO_LOYAL_CHANGE				= "LUA_EVENT_HERO_LOYAL_CHANGE"				-- 英雄忠诚度改变
LUA_EVENT_HERO_CALL_BUTTON_SHOW			= "LUA_EVENT_HERO_CALL_BUTTON_SHOW"			-- 英雄召唤按钮显示与否

LUA_EVENT_HERO_DIE						= "LUA_EVENT_HERO_DIE"						-- 英雄死亡
LUA_EVENT_HERO_REVIVE					= "LUA_EVENT_HERO_REVIVE"					-- 英雄复活

LUA_EVENT_HERO_MERIDIAN_DATA_REFRESH    = "LUA_EVENT_HERO_MERIDIAN_DATA_REFRESH"    -- 英雄内功经络数据刷新
LUA_EVENT_HERO_INTERNAL_DZVALUE_CHANGE  = "LUA_EVENT_HERO_INTERNAL_DZVALUE_CHANGE"  -- 内功斗转值改变/恢复

LUA_EVENT_HERO_COMBO_SKILL_ADD          = "LUA_EVENT_HERO_COMBO_SKILL_ADD"          -- 英雄连击技能增加
LUA_EVENT_HERO_COMBO_SKILL_DEL          = "LUA_EVENT_HERO_COMBO_SKILL_DEL"          -- 英雄连击技能删除
LUA_EVENT_HERO_COMBO_SKILL_UPDATE       = "LUA_EVENT_HERO_COMBO_SKILL_UPDATE"       -- 英雄连击技能刷新
LUA_EVENT_HERO_SET_COMBO_REFRESH        = "LUA_EVENT_HERO_SET_COMBO_REFRESH"        -- 英雄设置连击技能刷新
LUA_EVENT_HERO_OPEN_COMBO_NUM           = "LUA_EVENT_HERO_OPEN_COMBO_NUM"           -- 英雄开启连击个数

LUA_EVENT_HERO_PROPERTY_CHANGE          = "LUA_EVENT_HERO_PROPERTY_CHANGE"          -- 英雄属性变化

-- 小地图
LUA_EVENT_MINIMAP_FIND_PATH             = "LUA_EVENT_MINIMAP_FIND_PATH"             -- 寻路路径
LUA_EVENT_MINIMAP_MONSTER               = "LUA_EVENT_MINIMAP_MONSTER"               -- 怪物坐标
LUA_EVENT_MINIMAP_PLAYER                = "LUA_EVENT_MINIMAP_PLAYER"                -- 人物坐标
LUA_EVENT_MINIMAP_TEAM                  = "LUA_EVENT_MINIMAP_TEAM"                  -- 队伍坐标
LUA_EVENT_OTHER_MAP_MONSTER				= "LUA_EVENT_OTHER_MAP_MONSTER"				-- 其他地图怪物数据

LUA_EVENT_MINIMAP_BEGIN               	= "LUA_EVENT_MINIMAP_BEGIN"                 -- 打开小地图

-- 消息
LUA_EVENT_NOTICE_SERVER                 = "LUA_EVENT_NOTICE_SERVER"                 -- 消息 服务 (Type4)
LUA_EVENT_NOTICE_SERVER_EVENT           = "LUA_EVENT_NOTICE_SERVER_EVENT"           -- 消息 服务 枚举值 (Type11)
LUA_EVENT_NOTICE_SYSYTEM                = "LUA_EVENT_NOTICE_SYSYTEM"                -- 消息 系统 跑马灯 (Type5)
LUA_EVENT_NOTICE_SYSYTEM_SCALE          = "LUA_EVENT_NOTICE_SYSYTEM_SCALE"          -- 消息 系统 顶端弹窗 (Type13)
LUA_EVENT_NOTICE_SYSYTEM_XY             = "LUA_EVENT_NOTICE_SYSYTEM_XY"             -- 消息 系统 设置XY 跑马灯 (Type10)
LUA_EVENT_NOTICE_SYSYTEM_TIPS           = "LUA_EVENT_NOTICE_SYSYTEM_TIPS"           -- 消息 系统 提示弹窗 警告
LUA_EVENT_NOTICE_TIMER                  = "LUA_EVENT_NOTICE_TIMER"                  -- 消息 提示 警告 (Type6)
LUA_EVENT_NOTICE_DELETE_TIMER           = "LUA_EVENT_NOTICE_DELETE_TIMER"           -- 消息 提示 警告 
LUA_EVENT_NOTICE_TIMER_XY               = "LUA_EVENT_NOTICE_TIMER_XY"               -- 消息 提示 警告 设置XY (Type14)
LUA_EVENT_NOTICE_DELETE_TIMER_XY        = "LUA_EVENT_NOTICE_DELETE_TIMER_XY"        -- 消息 提示 警告 设置XY (Type14)
LUA_EVENT_NOTICE_ITEM_TIPS              = "LUA_EVENT_NOTICE_ITEM_TIPS"              -- 飘字 物品拾取获得消耗
LUA_EVENT_NOTICE_ATTRIBUTE              = "LUA_EVENT_NOTICE_ATTRIBUTE"              -- 飘字 属性变化
LUA_EVENT_NOTICE_EXP                    = "LUA_EVENT_NOTICE_EXP"                    -- 飘字 经验值变化
LUA_EVENT_NOTICE_DROP                   = "LUA_EVENT_NOTICE_DROP"                   -- 飘字 掉落物品提示 (Type15)
LUA_EVENT_NOTICE_CHILD_ADD				= "LUA_EVENT_NOTICE_CHILD_ADD"				-- notice 添加子节点
LUA_EVENT_NOTICE_CHILD_REMOVE			= "LUA_EVENT_NOTICE_CHILD_REMOVE"			-- notice 移除子节点

-- 合成
LUA_EVENT_COMPOUND_RED_POINT            = "LUA_EVENT_COMPOUND_RED_POINT"            -- 合成红点
LUA_EVENT_COMPOUND_ITEM_RESULT         	= "LUA_EVENT_COMPOUND_ITEM_RESULT"         	-- 合成物品结果

-- richText
LUA_EVENT_RICHTEXT_OPEN_URL             = "LUA_EVENT_RICHTEXT_OPEN_URL"             -- 富文本超链(href)点击触发

LUA_EVENT_KF_STATUS_CHANGE              = "LUA_EVENT_KF_STATUS_CHANGE"              -- 跨服状态改变
LUA_EVENT_QUICKUSE_DATA_OPER            = "LUA_EVENT_QUICKUSE_DATA_OPER"            -- 快捷栏道具数据变动触发
LUA_EVENT_QUICKUSE_ITEM_REFRESH         = "LUA_EVENT_QUICKUSE_ITEM_REFRESH"         -- 快捷栏界面刷新

-- 游戏世界
LUA_EVENT_MAIN_INIT						= "LUA_EVENT_MAIN_INIT"						-- 主界面初始化
LUA_EVENT_ENTER_WORLD                   = "LUA_EVENT_ENTER_WORLD"                   -- 进入游戏世界，主界面已经刷出来了
LUA_EVENT_LEAVE_WORLD                   = "LUA_EVENT_LEAVE_WORLD"                   -- 离开游戏世界 - 小退触发

-- 玩家状态刷新
LUA_EVENT_PLAYER_IN_SAFEZONE_CHANGE     = "LUA_EVENT_PLAYER_IN_SAFEZONE_CHANGE"     -- 主玩家安全区状态改变
LUA_EVENT_NET_PLAYER_IN_SAFEZONE_CHANGE = "LUA_EVENT_NET_PLAYER_IN_SAFEZONE_CHANGE" -- 网络玩家安全区状态改变

LUA_EVENT_PLAYER_STALL_STATUS_CHANGE 	= "LUA_EVENT_PLAYER_STALL_STATUS_CHANGE" 	-- 主玩家摆摊状态改变
LUA_EVENT_NET_PLAYER_STALL_STATUS_CHANGE= "LUA_EVENT_NET_PLAYER_STALL_STATUS_CHANGE"-- 网络玩家摆摊状态改变	

LUA_EVENT_PLAYER_HUSHEN_STATUS_CHANGE       = "LUA_EVENT_PLAYER_HUSHEN_STATUS_CHANGE"       -- 主玩家护身状态改变
LUA_EVENT_NET_PLAYER_HUSHEN_STATUS_CHANGE   = "LUA_EVENT_NET_PLAYER_HUSHEN_STATUS_CHANGE"   -- 网络玩家护身状态改变

LUA_EVENT_PLAYER_TEAM_STATUS_CHANGE     = "LUA_EVENT_PLAYER_TEAM_STATUS_CHANGE"     -- 主玩家组队状态改变
LUA_EVENT_NET_PLAYER_TEAM_STATUS_CHANGE = "LUA_EVENT_NET_PLAYER_TEAM_STATUS_CHANGE" -- 网络玩家组队状态改变

LUA_EVENT_MAIN_PLAYER_ACTION_ENDED      = "LUA_EVENT_MAIN_PLAYER_ACTION_ENDED"		-- 主玩家动作结束

-- 求购
LUA_EVENT_PURCHASE_ITEM_LIST_PULL       = "LUA_EVENT_PURCHASE_ITEM_LIST_PULL"       -- 求购列表返回
LUA_EVENT_PURCHASE_ITEM_LIST_COMPLETE   = "LUA_EVENT_PURCHASE_ITEM_LIST_COMPLETE"   -- 求购列表加载完成
LUA_EVENT_PURCHASE_SEARCH_ITEM_UPDATE   = "LUA_EVENT_PURCHASE_SEARCH_ITEM_UPDATE"   -- 求购搜索刷新
LUA_EVENT_PURCHASE_MYITEM_UPDATE        = "LUA_EVENT_PURCHASE_MYITEM_UPDATE"        -- 求购数据刷新(我的)
LUA_EVENT_PURCHASE_WORLDITEM_UPDATE     = "LUA_EVENT_PURCHASE_WORLDITEM_UPDATE"     -- 求购数据刷新(世界)

LUA_EVENT_FLYIN_BTN_ITEM_COMPLETE       = "LUA_EVENT_FLYIN_BTN_ITEM_COMPLETE"       -- item飞入指定按钮完成

LUA_EVENT_STORAGE_DATA_CHANGE           = "LUA_EVENT_STORAGE_DATA_CHANGE"           -- 仓库数据变动
LUA_EVENT_STORAGE_DATA_UPDATE           = "LUA_EVENT_STORAGE_DATA_UPDATE"           -- 仓库数据刷新
LUA_EVENT_STORAGE_ITEM_STATE            = "LUA_EVENT_STORAGE_ITEM_STATE"            -- 仓库状态
LUA_EVENT_STORAGE_SIZE_CHANGE           = "LUA_EVENT_STORAGE_SIZE_CHANGE"           -- 仓库格子数改变

-- 登录账号
LUA_EVENT_LOGIN_REGISTER_ACCOUNT_SUCCESS	= "LUA_EVENT_LOGIN_REGISTER_ACCOUNT_SUCCESS"	-- 账号注册成功
LUA_EVENT_LOGIN_ACCOUNT_SUCCESS				= "LUA_EVENT_LOGIN_ACCOUNT_SUCCESS"				-- 账号登录成功
LUA_EVENT_LOGIN_CHECK_TOKEN_SUCCESS			= "LUA_EVENT_LOGIN_CHECK_TOKEN_SUCCESS"			-- 账密效验成功
LUA_EVENT_LOGIN_CHECK_TOKEN_FAIL			= "LUA_EVENT_LOGIN_CHECK_TOKEN_FAIL"           	-- 账密效验失败
LUA_EVENT_LOGIN_CHANGE_PASSWORD_SUCCESS		= "LUA_EVENT_LOGIN_CHANGE_PASSWORD_SUCCESS"     -- 修改密码成功
LUA_EVENT_LOGIN_IDENTIFY_IDCARD_SUCCESS		= "LUA_EVENT_LOGIN_IDENTIFY_IDCARD_SUCCESS"     -- 实名认证成功
LUA_EVENT_LOGIN_CHANGE_MBQUESTION_SUCCESS	= "LUA_EVENT_LOGIN_CHANGE_MBQUESTION_SUCCESS"	-- 修改密保问题成功
LUA_EVENT_LOGIN_BIND_PHONE_SUCCESS			= "LUA_EVENT_LOGIN_BIND_PHONE_SUCCESS"			-- 绑定手机号成功
LUA_EVENT_LOGIN_CHANGE_BIND_PHONE_SUCCESS	= "LUA_EVENT_LOGIN_CHANGE_BIND_PHONE_SUCCESS"	-- 换绑手机号成功
LUA_EVENT_LOGIN_SHOW_IDENTIFY_UI			= "LUA_EVENT_LOGIN_SHOW_IDENTIFY_UI"			-- 实名认证界面显示
LUA_EVENT_LOGIN_SHOW_BIND_PHONE_UI			= "LUA_EVENT_LOGIN_SHOW_BIND_PHONE_UI"			-- 绑定手机号界面显示

-- 登录创角
LUA_EVENT_LOGIN_RAND_ROLE_NAME_REFRESH		= "LUA_EVENT_LOGIN_RAND_ROLE_NAME_REFRESH"		-- 创角随机角色名刷新
LUA_EVENT_LOGIN_DELETE_ROLE_SUCCESS			= "LUA_EVENT_LOGIN_DELETE_ROLE_SUCCESS"			-- 删除角色成功
LUA_EVENT_LOGIN_DELETE_ROLE_FAIL			= "LUA_EVENT_LOGIN_DELETE_ROLE_FAIL"			-- 删除角色失败
LUA_EVENT_LOGIN_CREATE_ROLE_SUCCESS			= "LUA_EVENT_LOGIN_CREATE_ROLE_SUCCESS"			-- 创建角色成功
LUA_EVENT_LOGIN_CREATE_ROLE_FAIL			= "LUA_EVENT_LOGIN_CREATE_ROLE_FAIL"			-- 创建角色失败
LUA_EVENT_LOGIN_RESTORE_ROLE_DATA_REFRESH	= "LUA_EVENT_LOGIN_RESTORE_ROLE_DATA_REFRESH"	-- 可恢复角色数据刷新
LUA_EVENT_LOGIN_SERVER_SUCCESS				= "LUA_EVENT_LOGIN_SERVER_SUCCESS"				-- 登录成功
LUA_EVENT_LOGIN_RESTORE_ROLE_SUCCESS		= "LUA_EVENT_LOGIN_RESTORE_ROLE_SUCCESS"		-- 恢复角色成功
LUA_EVENT_LOGIN_RESTORE_ROLE_FAIL			= "LUA_EVENT_LOGIN_RESTORE_ROLE_FAIL"			-- 恢复角色失败
LUA_EVENT_LOGIN_ROLE_INFO_DATA				= "LUA_EVENT_LOGIN_ROLE_INFO_DATA"				-- 登录角色数据
LUA_EVENT_LOGIN_ROLE_ENTER_GAME_DELAY		= "LUA_EVENT_LOGIN_ROLE_ENTER_GAME_DELAY"		-- 小退延迟进入游戏

-- 聊天
LUA_EVENT_CHAT_PANEL_CLOSE					= "LUA_EVENT_CHAT_PANEL_CLOSE"					-- 关闭聊天页
LUA_EVENT_CHAT_ENTER_CD						= "LUA_EVENT_CHAT_ENTER_CD"						-- 聊天进入CD
LUA_EVENT_CHAT_PRIVATE_TARGET				= "LUA_EVENT_CHAT_PRIVATE_TARGET"				-- 私聊对象
LUA_EVENT_CHAT_ITEM_ADD						= "LUA_EVENT_CHAT_ITEM_ADD"						-- 聊天页item新增

LUA_EVENT_CHATMINI_ITEM_ADD					= "LUA_EVENT_CHATMINI_ITEM_ADD"					-- 聊天主界面item新增
LUA_EVENT_CHAT_PCPRIVATE_ITEM_ADD			= "LUA_EVENT_CHAT_PCPRIVATE_ITEM_ADD"			-- PC私聊页item新增
LUA_EVENT_CHAT_PCGUILD_ITEM_ADD				= "LUA_EVENT_CHAT_PCGUILD_ITEM_ADD"				-- PC行会聊天页item新增

LUA_EVENT_CHAT_MSG_ADD						= "LUA_EVENT_CHAT_MSG_ADD"						-- 聊天信息新增
LUA_EVENT_CHAT_PUSH_INPUT					= "LUA_EVENT_CHAT_PUSH_INPUT"					-- 聊天输入内容补充
LUA_EVENT_CHAT_REPLACE_INPUT				= "LUA_EVENT_CHAT_REPLACE_INPUT"				-- 聊天输入内容替换
LUA_EVENT_CHAT_TARGET_CHANGE				= "LUA_EVENT_CHAT_TARGET_CHANGE"				-- 聊天对象改变
LUA_EVENT_CHAT_EX_NOTICE_ADD				= "LUA_EVENT_CHAT_EX_NOTICE_ADD"				-- 聊天置顶消息新增	
LUA_EVENT_CHAT_FAKE_DROP_OPEN_STATUS		= "LUA_EVENT_CHAT_FAKE_DROP_OPEN_STATUS"		-- 设置聊天假掉落开关状态
LUA_EVENT_CHAT_FAKE_DROP_STATUS_CHANGE		= "LUA_EVENT_CHAT_FAKE_DROP_STATUS_CHANGE"		-- 聊天假掉落开关状态改变
LUA_EVENT_CHAT_DROP_MSG_ADD					= "LUA_EVENT_CHAT_DROP_MSG_ADD"					-- 聊天框掉落消息新增
LUA_EVENT_CHAT_FAKE_DROP_MSG_SPEED			= "LUA_EVENT_CHAT_FAKE_DROP_MSG_SPEED"			-- 假掉落速度变化
LUA_EVENT_CHAT_AUTO_SHOUT_DELAY_TIME		= "LUA_EVENT_CHAT_AUTO_SHOUT_DELAY_TIME"		-- 设置自动喊话间隙


LUA_EVENT_CHAT_CHANNEL_RECEIVIND_TIPS		= "LUA_EVENT_CHAT_CHANNEL_RECEIVIND_TIPS"		-- 设置聊天频道接收状态提示
LUA_EVENT_CHAT_SEND_ERROR_RESULT			= "LUA_EVENT_CHAT_SEND_ERROR_RESULT"			-- 聊天发送失败结果
LUA_EVENT_PC_FILL_CHAT_INPUT				= "LUA_EVENT_PC_FILL_CHAT_INPUT"				-- 填充PC聊天输入框
LUA_EVENT_CHAT_MOBILE_AUTO_SHOUT			= "LUA_EVENT_CHAT_MOBILE_AUTO_SHOUT"			-- 手机端自动汉化

LUA_EVENT_MAIN_CLOSE_KEYBOARD				= "LUA_EVENT_MAIN_CLOSE_KEYBOARD"				-- 关闭键盘

LUA_EVENT_CHAT_SET_CHANNEL_RECEIVIND		= "LUA_EVENT_CHAT_SET_CHANNEL_RECEIVIND"		-- 设置聊天频道接收状态提示


-- 聊天拓展
LUA_EVENT_CHAT_EXTEND_EXIT_ACTION			= "LUA_EVENT_CHAT_EXTEND_EXIT_ACTION"			-- 聊天拓展退出动画

-- FuncDock
LUA_EVENT_FUNC_DOCK_OPTION_CHANGE			= "LUA_EVENT_FUNC_DOCK_OPTION_CHANGE"			-- 功能开关改变
LUA_EVENT_FUNC_DOCK_LOOK_PLAYER_INFO		= "LUA_EVENT_FUNC_DOCK_LOOK_PLAYER_INFO"		-- 功能查看玩家数据

-- QuickSelect
LUA_EVENT_QUICK_SELECT_TARGET				= "LUA_EVENT_QUICK_SELECT_TARGET"				-- 快速选择目标

-- 技能释放
LUA_EVENT_USER_INPUT_LAUNCH_SKILL			= "LUA_EVENT_USER_INPUT_LAUNCH_SKILL"			-- 用户技能输入

-- 物品自定义变量
LUA_EVENT_ITEM_CUSTOM_ATTR					= "LUA_EVENT_ITEM_CUSTOM_ATTR"

--
LUA_EVENT_MAIN_PROPERTY_ON_KEY_ENTER		= "LUA_EVENT_MAIN_PROPERTY_ON_KEY_ENTER"		-- 主界面键入enter键触发

-- 骑马
LUA_EVENT_HORSE_UP                      	= "LUA_EVENT_HORSE_UP"                      	-- 上马
LUA_EVENT_HORSE_DOWN                    	= "LUA_EVENT_HORSE_DOWN"                    	-- 下马

-------------------zfs begin------------------------------------------------------------------------------------
-----摆摊
LUA_EVENT_STALL_SELF_ITEM_CHANGE			= "LUA_EVENT_STALL_SELF_ITEM_CHANGE"				-- 摆摊自己的物品改变
LUA_EVENT_STALL_ITEM_LIST_CHANGE 			= "LUA_EVENT_STALL_ITEM_LIST_CHANGE"				-- 摆摊物品改变
LUA_EVENT_DARK_STATE_CHANGE              	= "LUA_EVENT_DARK_STATE_CHANGE"             		-- 黑夜状态改变
LUA_EVENT_MONSTER_IGNORELIST_ADD         	= "LUA_EVENT_MONSTER_IGNORELIST_ADD"        		-- 设置 怪物忽略列表增加
LUA_EVENT_BOSSTIPSLIST_ADD               	= "LUA_EVENT_BOSSTIPSLIST_ADD"              		-- 设置 boss提示 增加
LUA_EVENT_MONSTER_NAME_RM                	= "LUA_EVENT_MONSTER_NAME_RM"               		-- 设置 怪物类型删除
LUA_EVENT_SKILL_RANKDATA_ADD            	= "LUA_EVENT_SKILL_RANKDATA_ADD"            		-- 设置 技能数据添加
LUA_EVENT_SKILLBUTTON_DISTANCE_CHANGE    	= "LUA_EVENT_SKILLBUTTON_DISTANCE_CHANGE"   		-- 技能边距调整 
LUA_EVENT_TRADE_STALL_FORBID    			= "LUA_EVENT_TRADE_STALL_FORBID"   					-- 摆摊中禁止交易 

LUA_EVENT_PLAYER_FRAME_NAME_RRFRESH      	= "LUA_EVENT_PLAYER_FRAME_NAME_RRFRESH"     		-- 角色框刷新名字

LUA_EVENT_PLAYER_GUILD_INFO_CHANGE       	= "LUA_EVENT_PLAYER_GUILD_INFO_CHANGE"      		-- 玩家行会信息改变

LUA_EVENT_HERO_FRAME_NAME_RRFRESH        	= "LUA_EVENT_HERO_FRAME_NAME_RRFRESH"       		-- 英雄框刷新名字

LUA_EVENT_SERVER_VALUE_CHANGE             	= "LUA_EVENT_SERVER_VALUE_CHANGE"                 	-- 服务器下发的变量改变
LUA_EVENT_CHECK_SERVER_VALUE_CHANGE			= "LUA_EVENT_CHECK_SERVER_VALUE_CHANGE"				-- 检查服务器下发变量改变

LUA_EVENT_EQUIP_RETRIEVE_STATE_CHANGE	 	= "LUA_EVENT_EQUIP_RETRIEVE_STATE_CHANGE"			-- 背包状态改变
LUA_EVENT_ITEM_MOVE_BEGIN_BAG_POS_CHANGE	= "LUA_EVENT_ITEM_MOVE_BEGIN_BAG_POS_CHANGE"		-- 道具换位后开始拖动
LUA_EVENT_BAG_LOAD_SUCCESS					= "LUA_EVENT_BAG_LOAD_SUCCESS"						-- 背包加载完成
LUA_EVENT_HERO_BAG_LOAD_SUCCESS				= "LUA_EVENT_HERO_BAG_LOAD_SUCCESS"					-- 英雄背包加载完成
LUA_EVENT_PLAYER_IN_OF_VIEW                 = "LUA_EVENT_PLAYER_IN_OF_VIEW"                     -- 进视野
LUA_EVENT_PLAYER_OUT_OF_VIEW                = "LUA_EVENT_PLAYER_OUT_OF_VIEW"                    -- 出视野
LUA_EVENT_MAIN_NEAR_REFRESH                 = "LUA_EVENT_MAIN_NEAR_REFRESH" 

LUA_EVENT_MAIN_ADD_QUIT_TIME_TIPS			= "LUA_EVENT_MAIN_ADD_QUIT_TIME_TIPS"				-- 添加退出倒计时提示
LUA_EVENT_MAIN_DEL_QUIT_TIME_TIPS			= "LUA_EVENT_MAIN_DEL_QUIT_TIME_TIPS"				-- 移除退出倒计时提示

LUA_EVENT_MAIN_CHAT_EX_CLEAR				= "LUA_EVENT_MAIN_CHAT_EX_CLEAR"					-- 主界面ChatEx清空

LUA_EVENT_BESTRINGBOX_STATE         		= "LUA_EVENT_BESTRINGBOX_STATE"             		-- 首饰盒状态变化
LUA_EVENT_HERO_BESTRINGBOX_STATE          	= "LUA_EVENT_HERO_BESTRINGBOX_STATE"              	-- 英雄首饰盒

LUA_EVENT_PLAYER_SEX_CHANGE                 = "LUA_EVENT_PLAYER_SEX_CHANGE"                     -- 性别变化
LUA_EVENT_HERO_SEX_CHANGE					= "LUA_EVENT_HERO_SEX_CHANGE"						-- 英雄性别变化

LUA_EVENT_PLAYER_JOB_CHANGE                 = "LUA_EVENT_PLAYER_JOB_CHANGE"                     -- 人物职业变化
LUA_EVENT_HERO_JOB_CHANGE					= "LUA_EVENT_HERO_JOB_CHANGE"						-- 英雄职业变化

LUA_EVENT_SOCIAL_NRAR_PLAYER_LAYER_CLOSE	= "LUA_EVENT_SOCIAL_NRAR_PLAYER_LAYER_CLOSE"		-- 社交附近玩家关闭	
LUA_EVENT_SOCIAL_TEAM_LAYER_CLOSE			= "LUA_EVENT_SOCIAL_TEAM_LAYER_CLOSE"				-- 社交组队关闭	
LUA_EVENT_SOCIAL_FRIEND_LAYER_CLOSE			= "LUA_EVENT_SOCIAL_FRIEND_LAYER_CLOSE"				-- 社交好友关闭
LUA_EVENT_SOCIAL_MAIL_LAYER_CLOSE			= "LUA_EVENT_SOCIAL_MAIL_LAYER_CLOSE"				-- 社交邮件关闭	
LUA_EVENT_SOCIAL_RELATION_LAYER_CLOSE		= "LUA_EVENT_SOCIAL_RELATION_LAYER_CLOSE"			-- 社交关系关闭

LUA_EVENT_SOCIAL_TEAM_ERROR					= "LUA_EVENT_SOCIAL_TEAM_ERROR"						-- 组队异常
LUA_EVENT_SOCIAL_TEAM_CREATE				= "LUA_EVENT_SOCIAL_TEAM_CREATE"					-- 创建队伍
LUA_EVENT_SOCIAL_TEAM_REFUSE_APPLY			= "LUA_EVENT_SOCIAL_TEAM_REFUSE_APPLY"				-- 拒绝申请
LUA_EVENT_SOCIAL_TEAM_JOIN                  = "LUA_EVENT_SOCIAL_TEAM_JOIN"                      -- 加入队伍
LUA_EVENT_SOCIAL_TEAM_LEAVE					= "LUA_EVENT_SOCIAL_TEAM_LEAVE"						-- 离开队伍
LUA_EVENT_SOCIAL_TEAM_OUT					= "LUA_EVENT_SOCIAL_TEAM_OUT"						-- 被T出队伍
LUA_EVENT_SOCIAL_TEAM_DISMISS				= "LUA_EVENT_SOCIAL_TEAM_DISMISS"					-- 解散队伍
LUA_EVENT_SOCIAL_TEAM_OTHER_LEAVE			= "LUA_EVENT_SOCIAL_TEAM_OTHER_LEAVE"				-- 其他人离开
LUA_EVENT_SOCIAL_TEAM_REFUSE_INVITE			= "LUA_EVENT_SOCIAL_TEAM_REFUSE_INVITE"				-- 拒绝邀请
LUA_EVENT_TEAM_BEINVITED_UPDATE				= "LUA_EVENT_TEAM_BEINVITED_UPDATE"					-- 组队被邀请更新

LUA_EVENT_SOCIAL_FRIEND_ERROR				= "LUA_EVENT_SOCIAL_FRIEND_ERROR"						-- 好友异常
LUA_EVENT_SOCIAL_FRIEND_APPLY_SUCCESS		= "LUA_EVENT_SOCIAL_FRIEND_APPLY_SUCCESS"				-- 申请成功
LUA_EVENT_SOCIAL_FRIEND_ADD_SUCCESS			= "LUA_EVENT_SOCIAL_FRIEND_ADD_SUCCESS"					-- 增加成功
LUA_EVENT_SOCIAL_FRIEND_DEL_SUCCESS			= "LUA_EVENT_SOCIAL_FRIEND_DEL_SUCCESS"					-- 删除成功
LUA_EVENT_SOCIAL_FRIEND_DEL_BLACKLIST_SUCCESS	= "LUA_EVENT_SOCIAL_FRIEND_DEL_BLACKLIST_SUCCESS"	-- 删除黑名单成功
LUA_EVENT_SOCIAL_FRIEND_ADD_BLACKLIST_SUCCESS	= "LUA_EVENT_SOCIAL_FRIEND_ADD_BLACKLIST_SUCCESS"	-- 添加黑名单成功
LUA_EVENT_SOCIAL_FRIEND_REFUSE_APPLY		= "LUA_EVENT_SOCIAL_FRIEND_REFUSE_APPLY"				-- 拒绝好友申请

LUA_EVENT_SOCIAL_RELATION_INVITE_ERROR		= "LUA_EVENT_SOCIAL_RELATION_INVITE_ERROR"				-- 邀请建立关系异常
LUA_EVENT_SOCIAL_RELATION_DATA_INIT			= "LUA_EVENT_SOCIAL_RELATION_DATA_INIT"					-- 关系网数据初始化
LUA_EVENT_SOCIAL_RELATION_DATA_REFRESH		= "LUA_EVENT_SOCIAL_RELATION_DATA_REFRESH"				-- 关系网数据刷新
LUA_EVENT_SOCIAL_RELATION_NOTICE			= "LUA_EVENT_SOCIAL_RELATION_NOTICE"					-- 关系相关通知提示

LUA_EVENT_MAIN_JOYSTICKUPDATE 				= "LUA_EVENT_MAIN_JOYSTICKUPDATE"						--主界面摇杆更新
LUA_EVENT_MAIN_JOYSTICK_DISTANCE_CHANGE		= "LUA_EVENT_MAIN_JOYSTICK_DISTANCE_CHANGE"				--摇杆侧边距改变
LUA_EVENT_MAIN_ONE_DOUBLE_JOYSTICK			= "LUA_EVENT_MAIN_ONE_DOUBLE_JOYSTICK"					--单双摇杆改变设置改变

LUA_EVENT_TRADE_BANK_PLAYER_FRAME_CLOSE		= "LUA_EVENT_TRADE_BANK_PLAYER_FRAME_CLOSE"				--交易行查看他人关闭
-----------------------------------------------------------------背包网络事件
LUA_EVENT_REQ_BAGDATA						= "LUA_EVENT_REQ_BAGDATA"
LUA_EVENT_BAG_REQ_TWO_TO_ONE				= "LUA_EVENT_BAG_REQ_TWO_TO_ONE"
LUA_EVENT_BAG_REQ_NUMBER_CHANGE				= "LUA_EVENT_BAG_REQ_NUMBER_CHANGE"
LUA_EVENT_BAG_REQ_COLLIMATOR				= "LUA_EVENT_BAG_REQ_COLLIMATOR"
LUA_EVENT_BAG_REQ_CANCELCOLLIMATOR			= "LUA_EVENT_BAG_REQ_CANCELCOLLIMATOR"
LUA_EVENT_BAG_REQ_UNLOCK_BAG_SIZE			= "LUA_EVENT_BAG_REQ_UNLOCK_BAG_SIZE"

LUA_EVENT_RETURN_BAGDATA					= "LUA_EVENT_RETURN_BAGDATA"
LUA_EVENT_BAG_ADD_ITEM						= "LUA_EVENT_BAG_ADD_ITEM"
LUA_EVENT_BAG_DEL_ITEM						= "LUA_EVENT_BAG_DEL_ITEM"
LUA_EVENT_BAG_UPDATE_ITEM					= "LUA_EVENT_BAG_UPDATE_ITEM"
LUA_EVENT_BAG_ITEM_USE_SUCCESS				= "LUA_EVENT_BAG_ITEM_USE_SUCCESS"
LUA_EVENT_BAG_ITEM_USE_FAIL					= "LUA_EVENT_BAG_ITEM_USE_FAIL"
LUA_EVENT_DROP_ITEM_GET_FAIL				= "LUA_EVENT_DROP_ITEM_GET_FAIL"
LUA_EVENT_DROP_ITEM_SUCCESS					= "LUA_EVENT_DROP_ITEM_SUCCESS"
LUA_EVENT_DROP_ITEM_FAIL					= "LUA_EVENT_DROP_ITEM_FAIL"
LUA_EVENT_HUMBAG_TO_HEROBAG_FAIL			= "LUA_EVENT_HUMBAG_TO_HEROBAG_FAIL"
LUA_EVENT_RESET_BAG_POS						= "LUA_EVENT_RESET_BAG_POS"
LUA_EVENT_COLLIMATOR_RESPONSE				= "LUA_EVENT_COLLIMATOR_RESPONSE"
--hero
LUA_EVENT_HERO_BAG_REQ_TWO_TO_ONE 			= "LUA_EVENT_HERO_BAG_REQ_TWO_TO_ONE"
LUA_EVENT_HERO_BAG_REQ_NUMBER_CHANGE		= "LUA_EVENT_HERO_BAG_REQ_NUMBER_CHANGE"
LUA_EVENT_REQ_HUM_BAG_TO_HERO_BAG			= "LUA_EVENT_REQ_HUM_BAG_TO_HERO_BAG" 	
LUA_EVENT_REQ_HERO_BAG_TO_HUM_BAG			= "LUA_EVENT_REQ_HERO_BAG_TO_HUM_BAG"

LUA_EVENT_RETURN_HERO_BAGDATA				= "LUA_EVENT_RETURN_HERO_BAGDATA"
LUA_EVENT_HERO_BAG_ADD_ITEM					= "LUA_EVENT_HERO_BAG_ADD_ITEM"
LUA_EVENT_HERO_BAG_DEL_ITEM					= "LUA_EVENT_HERO_BAG_DEL_ITEM"
LUA_EVENT_HERO_BAG_UPDATE_ITEM				= "LUA_EVENT_HERO_BAG_UPDATE_ITEM"
LUA_EVENT_HERO_BAG_ITEM_USE_FAIL			= "LUA_EVENT_HERO_BAG_ITEM_USE_FAIL"
LUA_EVENT_HERO_DROP_ITEM_GET_FAIL			= "LUA_EVENT_HERO_DROP_ITEM_GET_FAIL"
LUA_EVENT_HERO_DROP_ITEM_SUCCESS			= "LUA_EVENT_HERO_DROP_ITEM_SUCCESS"
LUA_EVENT_HERO_DROP_ITEM_FAIL				= "LUA_EVENT_HERO_DROP_ITEM_FAIL"
LUA_EVENT_HERO_BAG_TO_HUMAN_BAG_FAIL		= "LUA_EVENT_HERO_BAG_TO_HUMAN_BAG_FAIL"


LUA_EVENT_BAG_UPDATE_ITEM_TIME					= "LUA_EVENT_BAG_UPDATE_ITEM_TIME"

-- 拍卖行
LUA_EVENT_AUCTION_PUT_IN					= "LUA_EVENT_AUCTION_PUT_IN"						-- 上架
LUA_EVENT_AUCTION_WORLD_ITEM_ADD			= "LUA_EVENT_AUCTION_WORLD_ITEM_ADD"				-- 拍卖物品增加
LUA_EVENT_AUCTION_ITEM_UPDATE				= "LUA_EVENT_AUCTION_ITEM_UPDATE"					-- 拍卖物品刷新
LUA_EVENT_AUCTION_PUT_OUT					= "LUA_EVENT_AUCTION_PUT_OUT"						-- 下架
LUA_EVENT_AUCTION_PUT_LIST					= "LUA_EVENT_AUCTION_PUT_LIST"						-- 上架列表
LUA_EVENT_AUCTION_BIDDING_LIST				= "LUA_EVENT_AUCTION_BIDDING_LIST"					-- 我的竞拍列表
LUA_EVENT_AUCTION_ITEM_LIST					= "LUA_EVENT_AUCTION_ITEM_LIST"						-- 竞拍物品列表
LUA_EVENT_AUCTION_ITEM_LIST_CLEAR			= "LUA_EVENT_AUCTION_ITEM_LIST_CLEAR"				-- 清理列表
LUA_EVENT_AUCTION_WORLD_ITEM_DEL			= "LUA_EVENT_AUCTION_WORLD_ITEM_DEL"				-- 拍卖物品删除
LUA_EVENT_AUCTION_WORLD_ITEM_CHANGE			= "LUA_EVENT_AUCTION_WORLD_ITEM_CHANGE"				-- 拍卖物品改变
LUA_EVENT_AUCTION_WORLD_ITEM_SEARCH			= "LUA_EVENT_AUCTION_WORLD_ITEM_SEARCH"				-- 拍卖物品查找
LUA_EVENT_AUCTION_BID			            = "LUA_EVENT_AUCTION_BID"				            -- 竞拍
LUA_EVENT_AUCTION_BID_ERRORCODE             = "LUA_EVENT_AUCTION_BID_ERRORCODE"
LUA_EVENT_AUCTION_ACQUIRE                   = "LUA_EVENT_AUCTION_ACQUIRE"                       -- 领取竞拍物品
-------------------zfs end------------------------------------------------------------------------------------


LUA_EVENT_TARGET_BELONG_SELECT				= "LUA_EVENT_TARGET_BELONG_SELECT"					-- 快捷归属选中
LUA_EVENT_USER_INPUT_MOVE					= "LUA_EVENT_USER_INPUT_MOVE"
------------------------------------------------------------------------------------------------------------------------
LUA_EVENT_COMMONTIPS_EVENT                  = "LUA_EVENT_COMMONTIPS_EVENT"

------------------------------------------------------------------------------------------------------------------------
-- 触发
LUA_TRIGGER_CHAT_CLICK_PLAYER_NAME      = "LUA_TRIGGER_CHAT_CLICK_PLAYER_NAME"      -- 触发，聊天点击玩家名字

LUA_TRIGGER_NOTICE_SHOW_ATTRIBUTES      = "LUA_TRIGGER_NOTICE_SHOW_ATTRIBUTES"      -- 提示通知--属性通知

LUA_TRIGGER_NOTICE_SHOW_GET_ITEM        = "LUA_TRIGGER_NOTICE_SHOW_GET_ITEM"        -- 提示通知--获得物品
LUA_TRIGGER_NOTICE_SHOW_COST_ITEM       = "LUA_TRIGGER_NOTICE_SHOW_COST_ITEM"       -- 提示通知--消耗物品

LUA_TRIGGER_NOTICE_SHOW_EXP_CHANGE      = "LUA_TRIGGER_NOTICE_SHOW_EXP_CHANGE"      -- 提示通知--经验通知

------------------------------------------------------------------------------------------------------------------------

LUA_EVENT_SKILL_ON                  	= "LUA_EVENT_SKILL_ON"
LUA_EVENT_SKILL_OFF                 	= "LUA_EVENT_SKILL_OFF"
LUA_EVENT_SKILL_CHANGE_KEY          	= "LUA_EVENT_SKILL_CHANGE_KEY"              -- 技能键改变
LUA_EVENT_SKILL_DELETE_KEY          	= "LUA_EVENT_SKILL_DELETE_KEY"              -- 删除技能键

LUA_EVENT_PLAYER_EQUIP_INIT         	= "LUA_EVENT_PLAYER_EQUIP_INIT"             -- 玩家装备数据初始化
LUA_EVENT_CLEAR_SELECT_SKILL        	= "LUA_EVENT_CLEAR_SELECT_SKILL"            -- 清空选中技能
LUA_EVENT_SKILL_CD_CHANGE           	= "LUA_EVENT_SKILL_CD_CHANGE"				-- 技能CD改变
LUA_EVENT_COMBO_SKILL_CD_CHANGE			= "LUA_EVENT_COMBO_SKILL_CD_CHANGE"			-- 连击技能CD改变

LUA_EVENT_HERO_LOCK_CHANGE				= "LUA_EVENT_HERO_LOCK_CHANGE"				-- 英雄锁定状态改变

LUA_EVENT_HERO_LOGIN                	= "LUA_EVENT_HERO_LOGIN"
LUA_EVENT_HERO_LOGOUT               	= "LUA_EVENT_HERO_LOGOUT"

LUA_EVENT_GUIDE_ENTER_TRANSITION		= "LUA_EVENT_GUIDE_ENTER_TRANSITION"		-- 引导切换
LUA_EVENT_GUIDE_EVENT_BEGAN             = "LUA_EVENT_GUIDE_EVENT_BEGAN"             -- 引导事件开始
LUA_EVENT_GUIDE_EVENT_ENDED             = "LUA_EVENT_GUIDE_EVENT_ENDED"             -- 引导事件结束
LUA_EVENT_GUIDE_EXIT					= "LUA_EVENT_GUIDE_EXIT"					-- 退出引导

LUA_EVENT_EQUIP_ATTR_REFRESH			= "LUA_EVENT_EQUIP_ATTR_REFRESH"			-- 装备属性刷新

LUA_EVENT_SKILL_ADD_TO_UI_WIN32 		= "LUA_EVENT_SKILL_ADD_TO_UI_WIN32" 		-- 添加技能到界面
LUA_EVENT_SKILL_DEL_TO_UI_WIN32  		= "LUA_EVENT_SKILL_DEL_TO_UI_WIN32"			-- 从界面删除技能

LUA_EVENT_TITLE_REFRESH					= "LUA_EVENT_TITLE_REFRESH"					-- 玩家称号刷新
LUA_EVENT_HERO_TITLE_REFRESH			= "LUA_EVENT_HERO_TITLE_REFRESH"			-- 英雄称号刷新

LUA_EVENT_GAME_MEMORY_RELEASE			= "LUA_EVENT_GAME_MEMORY_RELEASE"			-- 释放内存

------------------------------------------------------------------------------------------------------------------------
LUA_EVENT_COLLECT_VISIBLE				= "LUA_EVENT_COLLECT_VISIBLE"  				-- 自动 采集相关显示
LUA_EVENT_COLLECT_BEGIN					= "LUA_EVENT_COLLECT_BEGIN"  				-- 自动 开始
LUA_EVENT_COLLECT_COMPLETED				= "LUA_EVENT_COLLECT_COMPLETED"  			-- 自动 完成
LUA_EVENT_COLLECT_VISIBLE				= "LUA_EVENT_COLLECT_VISIBLE"  				-- 自动 采集相关显示
------------------------------------------------------------------------------------------------------------------------
-- 商城
LUA_EVENT_STORE_HOT_LAYER_CLOSE	        = "LUA_EVENT_STORE_HOT_LAYER_CLOSE"		    -- 商城热销关闭
LUA_EVENT_STORE_BEAUTY_LAYER_CLOSE	    = "LUA_EVENT_STORE_BEAUTY_LAYER_CLOSE"		-- 商城装饰界面关闭
LUA_EVENT_STORE_ENGINE_LAYER_CLOSE		= "LUA_EVENT_STORE_ENGINE_LAYER_CLOSE"		-- 商城功能界面关闭	
LUA_EVENT_STORE_FESTIVAL_LAYER_CLOSE	= "LUA_EVENT_STORE_FESTIVAL_LAYER_CLOSE"	-- 商城节日界面关闭
LUA_EVENT_STORE_RECHARGE_LAYER_CLOSE	= "LUA_EVENT_STORE_RECHARGE_LAYER_CLOSE"	-- 商城充值界面关闭	
LUA_EVENT_LAYER_PAGE_STORE_REFRESH	    = "LUA_EVENT_LAYER_PAGE_STORE_REFRESH"	    -- 商城界面刷新
LUA_EVENT_STORE_BUY_CLOSE               = "LUA_EVENT_STORE_BUY_CLOSE"               -- 商城物品购买界面关闭
LUA_EVENT_RECHARGE_RECEIVED             = "LUA_EVENT_RECHARGE_RECEIVED"             -- 充值结果
LUA_EVENT_NOT_FOUND_GOODS               = "LUA_EVENT_NOT_FOUND_GOODS"               -- 未找到商品

------------------------------------------------------------------------------------------------------------------------
LUA_EVENT_USERINPUT_EVENT_NOTICE        = "LUA_EVENT_USERINPUT_EVENT_NOTICE"        -- 用户输入事件通知
------------------------------------------------------------------------------------------------------------------------

---------------------------------------------------------------------------------------------------------------------------
LUA_EVENT_PC_SPELL_SCOPE_POS        		= "LUA_EVENT_PC_SPELL_SCOPE_POS"        -- pc 显示玩家移动坐标
LUA_EVENT_PC_SPELL_SCOPE_CELL        		= "LUA_EVENT_PC_SPELL_SCOPE_CELL"       -- pc 显示玩家施法范围格子
LUA_EVENT_PC_SPELL_SCOPE_SHOW_HIDE        	= "LUA_EVENT_PC_SPELL_SCOPE_SHOW_HIDE"  -- pc 施法范围显示隐藏
------------------------------------------------------------------------------------------------------------------------


-- 服务器开关
------------------------------------------------------------------------------------------------------------------------
SW_KEY_AUCTION                          = global.MMO.SERVER_OPTION_AUCTION             -- 服务器开关 拍卖
SW_KEY_ALL_FIGHTPAGES                   = global.MMO.SO_SHOW_ALL_FIGHTPAGES            -- 服务器开关 显示所有战斗页
SW_KEY_MISSTION                         = global.MMO.SERVER_OPTION_MISSTION            -- 服务器开关 任务
SW_KEY_BESTRINGBOX_SHOW                 = global.MMO.SERVER_OPTION_SNDAITEMBOX         -- 服务器开关 是否显示首饰盒
SW_KEY_TRADE_DEAL                       = global.MMO.SERVER_OPTION_TRADE_DEAL          -- 服务器开关 面对面交易 true/需要面对面
SW_KEY_AUTO_DRESS                       = global.MMO.SERVER_OPTION_AUTO_DRESS          -- 服务器开关 自动穿戴
SW_KEY_OPEN_F_EQUIP                     = global.MMO.SERVER_OPTION_OPEN_F_EQUIP        -- 服务器开关 时装是否开启首饰
SW_KEY_BIND_GOLD                        = global.MMO.SERVER_OPTION_BIND_GOLD           -- 服务器开关 开启元宝替换绑元
SW_KEY_NPC_BUTTON                       = global.MMO.SERVER_OPTION_NPC_BUTTON          -- 服务器开关 显示npc按钮
SW_KEY_NPC_NAME                         = global.MMO.SERVER_OPTION_NPC_NAME            -- 服务器开关 显示npc名字 1:不显示
SW_KEY_DROP_TIPS                        = global.MMO.SERVER_DROP_TIPS                  -- 服务器开关 显示绑定丢弃提示 0:显示
SW_KEY_EXP_IN_CHAT                      = global.MMO.SERVER_EXP_IN_CHAT                -- 服务器开关 经验信息是否显示在聊天框 0：显示在聊天框
SW_KEY_SHOW_STALL_NAME                  = global.MMO.SERVER_SHOW_STALL_NAME            -- 服务器开关 是否显示默认摊位名字  0：显示
SW_KEY_PLAYER_BLUE_BLOOD                = global.MMO.PLAYER_BLUE_BLOOD                 -- 服务器开关  是否显示蓝条HUD_SPRITE_MP   0: 显示
SW_KEY_ITEMTIPS_TOUBAO_SHOW             = global.MMO.ITEMTIPS_TOUBAO_SHOW              -- 服务器开关  是否显示itemtips的投保描述   1    = 开启 0       = 关闭
SW_KEY_BAN_DOUBLE_FIREHIT               = global.MMO.SERVER_OPTION_BAN_DOUBLE_FIREHIT  -- 服务器开关  是否禁止双烈火    1：禁止
SW_KEY_ALL_TEAM_EXP                     = global.MMO.SERVER_OPTION_ALL_TEAM_EXP        -- 服务器开关 是否开启全队经验 true/false
SW_KEY_EQUIP_EXTRA_POS     	            = global.MMO.EQUIP_EXTRA_POS	 	           -- 服务器开关，是否有额外的装备位置  1= 开启 0 = 关闭
SW_KEY_NO_SELL_MONEY                    = global.MMO.SERVER_NO_SELL_MONEY              -- 服务器开关，是否禁止交易货币  true = 禁止
SW_KEY_MAGIC_MISS_TYPE					= "MagicMissType"						       -- 服务器开关，魔法躲避属性类型 开启: 属性万分比 2
SW_KEY_ANTI_POISON_TYPE					= "AntiPoisonType"						       -- 服务器开关，毒物躲避、中毒恢复类型 开启: 属性万分比 2
SW_KEY_NEW_AUTO_SUMMON					= "CallMobSet"								   -- 服务器开关，开启新自动召唤
SW_KEY_NEW_AUTO_SUMMON_NEXT				= "UseLvNext"								   -- 服务器开关，新自动召唤是否顺延查找下一组召唤物
SW_KEY_NEW_AUTO_SUMMON_NUM				= "CallMobSetCnt"							   -- 服务器配置，新自动召唤最大数量
SW_KEY_BESTRINGBOX_NAME					= "SndaItemBoxName"							   -- 服务器配置, 首饰盒名称
SW_KEY_EAT_ITEM_SPEED					= "EatItemSpeed"						       -- 服务器配置, 吃物品速度

------------------------------------------------------------------------------------------------------------------------
	

SLDefine.SETTINGID = {
    SETTING_IDX_PLAYER_NAME          = global.MMO.SETTING_IDX_PLAYER_NAME           ,    -- 人物显名设置
	SETTING_IDX_HP_NUM               = global.MMO.SETTING_IDX_HP_NUM                ,    -- 数字显血设置
	SETTING_IDX_DAMAGE_NUM           = global.MMO.SETTING_IDX_DAMAGE_NUM            ,    -- 飘血显示设置
	SETTING_IDX_HP_HUD               = global.MMO.SETTING_IDX_HP_HUD                ,    -- 显示血条设置
	SETTING_IDX_MONSTER_NAME         = global.MMO.SETTING_IDX_MONSTER_NAME          ,    -- 怪物显名设置
	SETTING_IDX_ONE_DOUBLE_ROCKER    = global.MMO.SETTING_IDX_ONE_DOUBLE_ROCKER     ,    -- 单双摇杆
	SETTING_IDX_HP_LOW_USE_HCS       = global.MMO.SETTING_IDX_HP_LOW_USE_HCS        ,    -- 生命值低于多少使用回城石
	SETTING_IDX_HP_LOW_USE_SJS       = global.MMO.SETTING_IDX_HP_LOW_USE_SJS        ,    -- 生命值低于多少使用随机石
	SETTING_IDX_HP_LOW_USE_HY        = global.MMO.SETTING_IDX_HP_LOW_USE_HY         ,    -- 生命值低于多少使用HY
	SETTING_IDX_HP_LOW_USE_SHY       = global.MMO.SETTING_IDX_HP_LOW_USE_SHY        ,   -- 生命值低于多少使用SHY
	SETTING_IDX_MP_LOW_USE_LY        = global.MMO.SETTING_IDX_MP_LOW_USE_LY         ,   -- 魔法值低于多少使用LY
	SETTING_IDX_MP_LOW_USE_SHY       = global.MMO.SETTING_IDX_MP_LOW_USE_SHY        ,   -- 魔法值低于多少使用SHY
	SETTING_IDX_AUTO_MOVE            = global.MMO.SETTING_IDX_AUTO_MOVE             ,   -- 自动走位
	SETTING_IDX_ALWAYS_ATTACK        = global.MMO.SETTING_IDX_ALWAYS_ATTACK         ,   -- 持续攻击  
	SETTING_IDX_DAODAOCISHA          = global.MMO.SETTING_IDX_DAODAOCISHA           ,   -- 刀刀刺杀  
	SETTING_IDX_AUTO_LIEHUO          = global.MMO.SETTING_IDX_AUTO_LIEHUO           ,   -- 自动烈火
	SETTING_IDX_GEWEICISHA           = global.MMO.SETTING_IDX_GEWEICISHA            ,   -- 隔位刺杀
	SETTING_IDX_SMART_BANYUE         = global.MMO.SETTING_IDX_SMART_BANYUE          ,   -- 智能半月
	SETTING_IDX_AUTO_MOFADUN         = global.MMO.SETTING_IDX_AUTO_MOFADUN          ,   -- 自动魔法盾
	SETTING_IDX_AUTO_FIRE_WALL       = global.MMO.SETTING_IDX_AUTO_FIRE_WALL        ,   -- 自动火墙
	SETTING_IDX_AUTO_GROUPSKILL      = global.MMO.SETTING_IDX_AUTO_GROUPSKILL       ,   -- 群怪技能
	SETTING_IDX_AUTO_DU              = global.MMO.SETTING_IDX_AUTO_DU               ,   -- 自动施毒
	SETTING_IDX_AUTO_YOULINGDUN      = global.MMO.SETTING_IDX_AUTO_YOULINGDUN       ,   -- 自动幽灵盾
	SETTING_IDX_AUTO_SSZJS           = global.MMO.SETTING_IDX_AUTO_SSZJS            ,   -- 自动神圣战甲术
	SETTING_IDX_HP_LOW_USE_SKILL     = global.MMO.SETTING_IDX_HP_LOW_USE_SKILL      ,   -- 生命值低于多少使用 技能
	SETTING_IDX_AUTO_SUMMON          = global.MMO.SETTING_IDX_AUTO_SUMMON           ,   -- 自动召唤
	SETTING_IDX_BGMUSIC              = global.MMO.SETTING_IDX_BGMUSIC               ,   -- BG音乐
	SETTING_IDX_UNSAFE_TIPS          = global.MMO.SETTING_IDX_UNSAFE_TIPS           ,   -- 残血提示
	SETTING_IDX_CAMERA_ZOOM          = global.MMO.SETTING_IDX_CAMERA_ZOOM           ,   -- 摄像机zoom设置
	SETTING_IDX_SKILL_NEXT_ATTACK    = global.MMO.SETTING_IDX_SKILL_NEXT_ATTACK     ,   -- 技能接平砍
    SETTING_IDX_NOT_NEED_SHIFT       = global.MMO.SETTING_IDX_NOT_NEED_SHIFT        ,   -- 免shift
	SETTING_IDX_WINDOW_SMOOTH_VIEW   = global.MMO.SETTING_IDX_WINDOW_SMOOTH_VIEW    ,   -- PC端平滑模式
	SETTING_IDX_ONLY_NAME            = global.MMO.SETTING_IDX_ONLY_NAME             ,   -- 只显人名
	SETTING_IDX_PLAYER_JOB_LEVEL     = global.MMO.SETTING_IDX_PLAYER_JOB_LEVEL      ,   -- 主场景显示玩家职业等级模式设置
	SETTING_IDX_EXP_IGNORE           = global.MMO.SETTING_IDX_EXP_IGNORE            ,   -- 经验过滤
	SETTING_IDX_FIRE_OPACITY         = global.MMO.SETTING_IDX_FIRE_OPACITY          ,   -- 火墙淡化
	SETTING_IDX_EQUIP_COMPARE        = global.MMO.SETTING_IDX_EQUIP_COMPARE         ,   -- 装备对比
	SETTING_IDX_MAGIC_LOCK           = global.MMO.SETTING_IDX_MAGIC_LOCK            ,   -- 魔法锁定
	SETTING_IDX_AUTO_LAUNCH          = global.MMO.SETTING_IDX_AUTO_LAUNCH           ,   -- 自动练功
	SETTING_IDX_HIDE_MONSTER_BODY    = global.MMO.SETTING_IDX_HIDE_MONSTER_BODY     ,   -- 清理尸体
	SETTING_IDX_SPELL_HELP    		 = global.MMO.SETTING_IDX_SPELL_HELP     		,   -- 施法辅助
	SETTING_IDX_DU_FU_AUTOCHANGE     = global.MMO.SETTING_IDX_DU_FU_AUTOCHANGE      ,   -- 毒符互换
	SETTING_IDX_BB_ATTACK_WITH       = global.MMO.SETTING_IDX_BB_ATTACK_WITH        ,   -- 宝宝跟随攻击
    SETTING_IDX_NEAR_LIEHUO          = global.MMO.SETTING_IDX_NEAR_LIEHUO           ,   -- 近身烈火
	SETTING_IDX_BOSS_TIPS            = global.MMO.SETTING_IDX_BOSS_TIPS             ,   -- boss提示
	SETTING_IDX_AUTO_SIMPSKILL       = global.MMO.SETTING_IDX_AUTO_SIMPSKILL        ,   -- 单体技能
	SETTING_IDX_DURABILITY_TIPS      = global.MMO.SETTING_IDX_DURABILITY_TIPS       ,   -- 耐久提示
	SETTING_IDX_AUTO_REPAIR          = global.MMO.SETTING_IDX_AUTO_REPAIR           ,   -- 自动修理
	SETTING_IDX_EFFECTMUSIC          = global.MMO.SETTING_IDX_EFFECTMUSIC           ,   -- 游戏音乐
	SETTING_IDX_AUTO_KAITIAN         = global.MMO.SETTING_IDX_AUTO_KAITIAN          ,   -- 自动开天
	SETTING_IDX_AUTO_ZHURI           = global.MMO.SETTING_IDX_AUTO_ZHURI            ,   -- 自动逐日
	SETTING_IDX_AUTO_CLOAKING        = global.MMO.SETTING_IDX_AUTO_CLOAKING         ,   -- 自动隐身
	SETTING_IDX_MOVE_GEWEI_CISHA     = global.MMO.SETTING_IDX_MOVE_GEWEI_CISHA      ,   -- 移动隔位刺杀
	SETTING_IDX_PLAYER_SIMPLE_DRESS  = global.MMO.SETTING_IDX_PLAYER_SIMPLE_DRESS   ,   -- 人物简装
	SETTING_IDX_MONSTER_SIMPLE_DRESS = global.MMO.SETTING_IDX_MONSTER_SIMPLE_DRESS  ,   -- 怪物简装
    SETTING_IDX_BOSS_NO_SIMPLE_DRESS = global.MMO.SETTING_IDX_BOSS_NO_SIMPLE_DRESS  ,      -- Boss不简装
	SETTING_IDX_AUTO_WJZQ            = global.MMO.SETTING_IDX_AUTO_WJZQ             ,   -- 自动无极真气
	SETTING_IDX_ROCKER_CANCEL_ATTACK = global.MMO.SETTING_IDX_ROCKER_CANCEL_ATTACK  ,   -- 摇杆取消攻击
	SETTING_IDX_TITLE_VISIBLE        = global.MMO.SETTING_IDX_TITLE_VISIBLE         ,   -- 显示称号设置
	SETTING_IDX_AUTO_PUT_IN_EQUIP    = global.MMO.SETTING_IDX_AUTO_PUT_IN_EQUIP     ,   -- 装备自动穿戴读表
	SETTING_IDX_LEVEL_SHOW_NAME_HUD  = global.MMO.SETTING_IDX_LEVEL_SHOW_NAME_HUD   ,   -- 不选中状态,满足等级显示玩家名字HUD
	SETTING_IDX_AUTO_FIGHT_BACK      = global.MMO.SETTING_IDX_AUTO_FIGHT_BACK       ,   -- 自动反击
	SETTING_IDX_HP_UNIT              = global.MMO.SETTING_IDX_HP_UNIT               ,   -- hp血量单位转换
	SETTING_IDX_LAYER_OPACITY        = global.MMO.SETTING_IDX_LAYER_OPACITY         ,   -- Layer Opacity
	SETTING_IDX_DISCARD_GOODS        = global.MMO.SETTING_IDX_DISCARD_GOODS			,   -- 丢弃物品  
	SETTING_IDX_ROCKER_SHOW_DISTANCE = global.MMO.SETTING_IDX_ROCKER_SHOW_DISTANCE  ,   -- 轮盘侧边距离
	SETTING_IDX_SKILL_SHOW_DISTANCE  = global.MMO.SETTING_IDX_SKILL_SHOW_DISTANCE   ,   -- 技能侧边距离
	SETTING_IDX_MP_LOW_USE_HCS       = global.MMO.SETTING_IDX_MP_LOW_USE_HCS        ,   -- 魔法值低于多少使用回城石
	SETTING_IDX_MP_LOW_USE_SJS       = global.MMO.SETTING_IDX_MP_LOW_USE_SJS        ,   -- 魔法值低于多少使用随机石
	SETTING_IDX_AUTO_SHIELD_OF_FORCE = global.MMO.SETTING_IDX_AUTO_SHIELD_OF_FORCE  ,   -- 武力盾
	SETTING_IDX_AUTO_SHIELD_OF_TAOIST= global.MMO.SETTING_IDX_AUTO_SHIELD_OF_TAOIST ,  	-- 道力盾
	SETTING_IDX_FIRE_OWN_HIGHTLIGHT	 = global.MMO.SETTING_IDX_FIRE_OWN_HIGHTLIGHT	,	-- 自己火墙高亮
    SETTING_IDX_AUTO_ICE_PALM        = global.MMO.SETTING_IDX_AUTO_ICE_PALM 	    ,  -- 自动寒冰掌
	SETTING_IDX_AUTO_BLOODTHIRSTY_S  = global.MMO.SETTING_IDX_AUTO_BLOODTHIRSTY_S   ,  -- 自动嗜血术
	SETTING_IDX_AUTO_BREACH_NERVE_FU = global.MMO.SETTING_IDX_AUTO_BREACH_NERVE_FU  ,  -- 自动裂神符
	SETTING_IDX_AUTO_DEATH_EYE       = global.MMO.SETTING_IDX_AUTO_DEATH_EYE  	    ,  -- 自动死亡之眼
	SETTING_IDX_AUTO_ICE_SICKLE_S    = global.MMO.SETTING_IDX_AUTO_ICE_SICKLE_S     ,  -- 自动冰镰术
	SETTING_IDX_AUTO_FLAME_ICE       = global.MMO.SETTING_IDX_AUTO_FLAME_ICE        ,  -- 自动火焰冰
	SETTING_IDX_AUTO_ICE_GROUP_RAIN  = global.MMO.SETTING_IDX_AUTO_ICE_GROUP_RAIN   ,  -- 自动冰霜群雨
	SETTING_IDX_AUTO_DOUBLE_DRAGON_Z = global.MMO.SETTING_IDX_AUTO_DOUBLE_DRAGON_Z  ,  -- 自动双龙斩
	SETTING_IDX_AUTO_DRAGON_SHADOW_JF = global.MMO.SETTING_IDX_AUTO_DRAGON_SHADOW_JF ,  -- 自动龙影剑法
	SETTING_IDX_AUTO_THUNDERBOLT_JF  = global.MMO.SETTING_IDX_AUTO_THUNDERBOLT_JF   ,  -- 自动雷霆剑法
	SETTING_IDX_AUTO_FREELY_JS       = global.MMO.SETTING_IDX_AUTO_FREELY_JS        ,  -- 自动纵横剑术
    SETTING_IDX_PICK_SETTING         = global.MMO.SETTING_IDX_PICK_SETTING          ,  -- 拾取设置
    SETTING_IDX_AUTO_COMBO           = global.MMO.SETTING_IDX_AUTO_COMBO            ,  -- 自动连击
    SETTING_IDX_IGNORE_STALL         = global.MMO.SETTING_IDX_IGNORE_STALL          ,  -- 屏蔽摆摊
	SETTING_IDX_FRAME_RATE_TYPE_HIGH = global.MMO.SETTING_IDX_FRAME_RATE_TYPE_HIGH  , -- 高帧率模式设置
	SETTING_IDX_MONSTER_PET_VISIBLE  = global.MMO.SETTING_IDX_MONSTER_PET_VISIBLE   , -- 屏蔽物显示设置
	SETTING_IDX_EFFECT_SHOW          = global.MMO.SETTING_IDX_EFFECT_SHOW           , -- 屏蔽特效设置
	SETTING_IDX_PLAYER_SHOW_FRIEND   = global.MMO.SETTING_IDX_PLAYER_SHOW_FRIEND    , -- 屏蔽己方玩家设置
	SETTING_IDX_PLAYER_SHOW          = global.MMO.SETTING_IDX_PLAYER_SHOW           , -- 屏蔽玩家设置
	SETTING_IDX_MONSTER_VISIBLE      = global.MMO.SETTING_IDX_MONSTER_VISIBLE       , -- 屏蔽怪物设置
	SETTING_IDX_HERO_HIDE            = global.MMO.SETTING_IDX_HERO_HIDE             , -- 屏蔽英雄
	SETTING_IDX_HERO_JOINT_SHAKE     = global.MMO.SETTING_IDX_HERO_JOINT_SHAKE      , -- 合击震屏
	SETTING_IDX_HERO_AUTO_JOINT      = global.MMO.SETTING_IDX_HERO_AUTO_JOINT       , -- 自动合击
	SETTING_IDX_HERO_FOLLOW_ATTACK   = global.MMO.SETTING_IDX_HERO_FOLLOW_ATTACK    , -- 跟随主角攻击
	SETTING_IDX_HERO_ATTACK_DODGE    = global.MMO.SETTING_IDX_HERO_ATTACK_DODGE     , -- 英雄打怪躲避
	SETTING_IDX_HERO_AUTO_LOGIN      = global.MMO.SETTING_IDX_HERO_AUTO_LOGIN       , -- 自动召唤英雄
	SETTING_IDX_HERO_AUTO_LOGINOUT   = global.MMO.SETTING_IDX_HERO_AUTO_LOGINOUT    , -- 英雄残血自动收回
    SETTING_IDX_REVIVE_PROTECT       = global.MMO.SETTING_IDX_REVIVE_PROTECT        , -- 复活戒指回城保护
	SETTING_IDX_REVIVE_PROTECT_HERO  = global.MMO.SETTING_IDX_REVIVE_PROTECT_HERO   , -- 复活戒指回城保护 英雄
	SETTING_IDX_SKILL_EFFECT_SHOW    = global.MMO.SETTING_IDX_SKILL_EFFECT_SHOW     , -- 屏蔽技能特效
	SETTING_IDX_AUTO_SHI_ZI_HOU 	 = global.MMO.SETTING_IDX_AUTO_SHI_ZI_HOU		, -- 自动狮子吼
	SETTING_IDX_PLAYER_NAME_COLOR    = global.MMO.SETTING_IDX_PLAYER_NAME_COLOR		, -- 玩家名字变色
	SETTING_IDX_MORE_FAST 		     = global.MMO.SETTING_IDX_MORE_FAST 			, -- 更快的加速
	----人物保护
	SETTING_IDX_HP_PROTECT1          = global.MMO.SETTING_IDX_HP_PROTECT1           , -- hp保护1
	SETTING_IDX_HP_PROTECT2          = global.MMO.SETTING_IDX_HP_PROTECT2           , -- hp保护2
	SETTING_IDX_HP_PROTECT3          = global.MMO.SETTING_IDX_HP_PROTECT3           , -- hp保护3
	SETTING_IDX_HP_PROTECT4          = global.MMO.SETTING_IDX_HP_PROTECT4           , -- hp保护4
	SETTING_IDX_MP_PROTECT1          = global.MMO.SETTING_IDX_MP_PROTECT1           , -- mp保护1
	SETTING_IDX_MP_PROTECT2          = global.MMO.SETTING_IDX_MP_PROTECT2           , -- mp保护2
	SETTING_IDX_MP_PROTECT3          = global.MMO.SETTING_IDX_MP_PROTECT3           , -- mp保护3
	SETTING_IDX_MP_PROTECT4          = global.MMO.SETTING_IDX_MP_PROTECT4           , -- mp保护4
	----hero保护
	SETTING_IDX_HERO_HP_PROTECT1     = global.MMO.SETTING_IDX_HERO_HP_PROTECT1      , -- hp保护1
	SETTING_IDX_HERO_HP_PROTECT2     = global.MMO.SETTING_IDX_HERO_HP_PROTECT2      , -- hp保护2
	SETTING_IDX_HERO_HP_PROTECT3     = global.MMO.SETTING_IDX_HERO_HP_PROTECT3      , -- hp保护3
	SETTING_IDX_HERO_HP_PROTECT4     = global.MMO.SETTING_IDX_HERO_HP_PROTECT4      , -- hp保护4
	SETTING_IDX_HERO_MP_PROTECT1     = global.MMO.SETTING_IDX_HERO_MP_PROTECT1      , -- mp保护1
	SETTING_IDX_HERO_MP_PROTECT2     = global.MMO.SETTING_IDX_HERO_MP_PROTECT2      , -- mp保护2
	SETTING_IDX_HERO_MP_PROTECT3     = global.MMO.SETTING_IDX_HERO_MP_PROTECT3      , -- mp保护3
	SETTING_IDX_HERO_MP_PROTECT4     = global.MMO.SETTING_IDX_HERO_MP_PROTECT4      , -- mp保护4

	SETTING_IDX_PK_PROTECT           = global.MMO.SETTING_IDX_PK_PROTECT            , -- 红名保护
	SETTING_IDX_BEDAMAGED_PLAYER     = global.MMO.SETTING_IDX_BEDAMAGED_PLAYER      , -- 被玩家攻击时
	SETTING_IDX_N_RANGE_NO_PICK      = global.MMO.SETTING_IDX_N_RANGE_NO_PICK       , -- N范围内有多少怪 不走去拾取
	SETTING_IDX_FIRST_ATTACK_MASTER  = global.MMO.SETTING_IDX_FIRST_ATTACK_MASTER   , -- 受到BB攻击时先打主人
	SETTING_IDX_NO_ATTACK_HAVE_BELONG= global.MMO.SETTING_IDX_NO_ATTACK_HAVE_BELONG , -- 不抢别人归属怪物
	SETTING_IDX_NO_MONSTER_USE	     = global.MMO.SETTING_IDX_NO_MONSTER_USE        , -- 多少秒没怪物使用
	SETTING_IDX_BESIEGE_FLEE         = global.MMO.SETTING_IDX_BESIEGE_FLEE          , -- 周围有多少敌人时使用
	SETTING_IDX_RED_BESIEGE_FLEE     = global.MMO.SETTING_IDX_RED_BESIEGE_FLEE      , -- 周围有多少红名时使用
	SETTING_IDX_ENEMY_ATTACK         = global.MMO.SETTING_IDX_ENEMY_ATTACK          , -- 周围有敌人时主动攻击
	SETTING_IDX_IGNORE_MONSTER       = global.MMO.SETTING_IDX_IGNORE_MONSTER        , -- 自动挂机忽略的怪物
} 

-- F6可视化配置表
SLDefine.ConfigSettingFile = {
    [1]   = "cfg_att_score.lua",
    [2]   = "cfg_auction_type.lua",
    [3]   = "cfg_buff.lua",
    [4]   = "cfg_damage_number.lua",
    [5]   = "cfg_game_data.lua",
    [6]   = "cfg_magicinfo.lua",
    [7]   = "cfg_mapdesc.lua",
    [8]   = "cfg_setup.lua",
    [9]   = "cfg_skill_present.lua",
    [10]  = "cfg_sound.lua",
    [11]  = "cfg_PulsDesc.lua",
}


SLDefine.SUIComponentTable = global.SUIComponentTable

-- F6服务下发配置表
SLDefine.ConfigServerFile = {
    [1]   = "cfg_buff",
}

SLDefine.SHADER_TYPE = {
	-- shader
	SHADER_TYPE_HIGHTLIGHT           = global.MMO.SHADER_TYPE_HIGHTLIGHT            , -- shader type 1
	SHADER_TYPE_GOLDEN               = global.MMO.SHADER_TYPE_GOLDEN                , -- shader type 2
	SHADER_TYPE_SHADOW               = global.MMO.SHADER_TYPE_SHADOW                , -- shader type 3
	SHADER_TYPE_SLOW                 = global.MMO.SHADER_TYPE_SLOW                  , -- shader type 4
	SHADER_TYPE_OUTLINE              = global.MMO.SHADER_TYPE_OUTLINE               , -- shader type 5
	SHADER_TYPE_ICE                  = global.MMO.SHADER_TYPE_ICE                   , -- shader type 6
	SHADER_TYPE_HIGHTLIGHT_COVER     = global.MMO.SHADER_TYPE_HIGHTLIGHT_COVER      , -- shader type 7
	SHADER_TYPE_BLUR                 = global.MMO.SHADER_TYPE_BLUR                  , -- shader type 8
	SHADER_TYPE_ICE_ALPHA_MULTIP     = global.MMO.SHADER_TYPE_ICE_ALPHA_MULTIP      , -- shader type 9
	SHADER_TYPE_GRAY				 = 10,
	SHADER_TYPE_NORMAL				 = 11,
	SHADER_TYPE_ICE_ALPHA_ENHANCE 	 = global.MMO.SHADER_TYPE_ICE_ALPHA_ENHANCE 		, -- shader type 12
}

-- 背包默认数目
SLDefine.MAX_ITEM_NUMBER = global.MMO.MAX_ITEM_NUMBER

-- 快捷栏个数
SLDefine.QUICK_USE_SIZE = global.MMO.QUICK_USE_SIZE

--角色方向
SLDefine.Direction = {
	UP  			= global.MMO.ORIENT_U,
	RIGHT_UP		= global.MMO.ORIENT_RU,
	RIGHT			= global.MMO.ORIENT_R,
	RIGHT_BOTTOM	= global.MMO.ORIENT_RB,
	BOTTOM			= global.MMO.ORIENT_B,
	LEFT_BOTTOM		= global.MMO.ORIENT_LB,
	LEFT			= global.MMO.ORIENT_L,
	LEFT_UP			= global.MMO.ORIENT_LU,
	INVALID			= global.MMO.ORIENT_INVAILD
}

-- 公共资源路径
SLDefine.PATH_RES_PUBLIC = global.MMO.PATH_RES_PUBLIC
-- 公共win32资源路径
SLDefine.PATH_RES_PUBLIC_WIN32 = global.MMO.PATH_RES_PUBLIC_WIN32

-- 文件可写路径
SLDefine.WritablePath = global.WritablePath

--键盘keyCode
SLDefine.KeyCode = cc.KeyCode	

SLDefine.HudIndex = {
	HUD_LABEL_NAME                = global.MMO.HUD_LABEL_NAME,              	-- 名字
	HUD_LABEL_GUILD               = global.MMO.HUD_LABEL_GUILD,              	-- 工会名字
	HUD_LABEL_HP                  = global.MMO.HUD_LABEL_HP,              		-- 血量
	HUD_LABEL_PRE_NAME0           = global.MMO.HUD_LABEL_PRE_NAME0,            	-- 预留名字前缀0 名字同行
	HUD_LABEL_PRE_NAME1           = global.MMO.HUD_LABEL_PRE_NAME1,            	-- 预留名字前缀1
	HUD_LABEL_PRE_NAME2           = global.MMO.HUD_LABEL_PRE_NAME2,             -- 预留名字前缀2
	HUD_LABEL_PRE_NAME3           = global.MMO.HUD_LABEL_PRE_NAME3,             -- 预留名字前缀3
	HUD_LABEL_PRE_NAME4           = global.MMO.HUD_LABEL_PRE_NAME4,             -- 预留名字前缀4
	HUD_LABEL_PRE_NAME5           = global.MMO.HUD_LABEL_PRE_NAME5,             -- 预留名字前缀5
	HUD_LABEL_PRE_NAME6           = global.MMO.HUD_LABEL_PRE_NAME6,             -- 预留名字前缀6
	HUD_LABEL_PRE_NAME7           = global.MMO.HUD_LABEL_PRE_NAME7,             -- 预留名字前缀7
	HUD_LABEL_PRE_NAME8           = global.MMO.HUD_LABEL_PRE_NAME8,             -- 预留名字前缀8
	HUD_LABEL_PRE_NAME9           = global.MMO.HUD_LABEL_PRE_NAME9,             -- 预留名字前缀9
	HUD_LABEL_PRE_NAME10          = global.MMO.HUD_LABEL_PRE_NAME10,            -- 预留名字前缀10
	HUD_LABEL_PRE_NAME11          = global.MMO.HUD_LABEL_PRE_NAME11,            -- 预留名字前缀11
	HUD_LABEL_PRE_NAME12          = global.MMO.HUD_LABEL_PRE_NAME12,            -- 预留名字前缀12
	HUD_LABEL_TITLE_1             = global.MMO.HUD_LABEL_TITLE_1,             	-- 称号1
	HUD_LABEL_TITLE_2             = global.MMO.HUD_LABEL_TITLE_2,             	-- 称号2
	HUD_LABEL_TITLE_3             = global.MMO.HUD_LABEL_TITLE_3,             	-- 称号3
}

SLDefine.MapGrid = {
	MapGridWidth = global.MMO.MapGridWidth,					-- 地图格子宽度  48
	MapGridHeight = global.MMO.MapGridHeight,				-- 地图格子高度  32
}

SLDefine.SceneZOrder = {
	-- scene zOrder
	NODE_NUM 			     	= global.MMO.NODE_NUM,
	NODE_ROOT 					= global.MMO.NODE_ROOT,         				-- 10000
	NODE_GAME_WORLD 		    = global.MMO.NODE_GAME_WORLD,         			-- 10023
		NODE_MAP 					= global.MMO.NODE_MAP,         				-- 10003
		NODE_MAP_SLICE 				= global.MMO.NODE_MAP_SLICE,         		-- 10006
		NODE_SKILL_BEHIND 			= global.MMO.NODE_SKILL_BEHIND,         	-- 10034
		NODE_ACTOR 					= global.MMO.NODE_ACTOR,         			-- 10004
		NODE_ACTOR_SHADOW 			= global.MMO.NODE_ACTOR_SHADOW,         	-- 10007
		NODE_ACTOR_CLONE_SHADOW 	= global.MMO.NODE_ACTOR_CLONE_SHADOW,   	-- 10030
			NODE_ACTOR_NPC_SHADOW 		= global.MMO.NODE_ACTOR_NPC_SHADOW,  	-- 10031
			NODE_ACTOR_MONSTER_SHADOW 	= global.MMO.NODE_ACTOR_MONSTER_SHADOW, -- 10032
			NODE_ACTOR_PLAYER_SHADOW 	= global.MMO.NODE_ACTOR_PLAYER_SHADOW,  -- 10033
		NODE_ACTOR_SFX_BEHIND 		= global.MMO.NODE_ACTOR_SFX_BEHIND,         -- 10016
		NODE_ACTOR_SPRITE			= global.MMO.NODE_ACTOR_SPRITE,        		-- 10008
		NODE_ACTOR_SFX_FRONT 		= global.MMO.NODE_ACTOR_SFX_FRONT,        	-- 10010
		NODE_MAP_OBJ 				= global.MMO.NODE_MAP_OBJ,        			-- 10035
		NODE_SKILL 					= global.MMO.NODE_SKILL,        			-- 10015
		NODE_ACTOR_HUD 				= global.MMO.NODE_ACTOR_HUD,        		-- 10009
		NODE_DAMAGE 				= global.MMO.NODE_DAMAGE,        			-- 10017
	NODE_UI 					= global.MMO.NODE_UI,        					-- 10005
		NODE_UI_NORMAL 				= global.MMO.NODE_UI_NORMAL,        		-- 10011
		NODE_UI_TOPMOST 			= global.MMO.NODE_UI_TOPMOST,        		-- 10012
}

-- 功能开关
SLDefine.FuncDockOption = {
	ALLOW_ADD_FRIEND			= 1,
	ALLOW_TRADE	  	  			= 2,
	ALLOW_SHOW_FASHTION 		= 3,
	ALLOW_TEAM	  	  			= 4,
	ALLOW_NEAR_SHOW	  			= 5,		
	ALLOW_SHOW_HERO_FASHTION	= 6,
}

-- 行会成员等级
SLDefine.GuildRank = {
    Chairman        = 0,        -- 会长
    ViceChairman    = 1,        -- 副会长
    Elite           = 2,        -- 精英
    Member          = 3,        -- 会员
    Rank5           = 4,        -- 会员
}

--交易行玩家面板 页签
SLDefine.TradingBankPlayerPages = {
	Equip = 1 ,
    BaseAtt = 2,
    ExtraAtt = 3,
    Skill = 4,
    Title = 5,
    SuperEquip = 6,
    Bag = 7,   --背包
    Storage = 8 --仓库
}

SLDefine.HyperLinkID = {
    Equip               = 1,            -- 角色-装备
    State               = 2,            -- 角色-状态
    Attri               = 3,            -- 角色-属性
    Skill               = 4,            -- 角色-技能
    Title               = 5,            -- 角色-装备
    BestRing            = 6,            -- 角色-首饰盒
    Bag                 = 7,            -- 背包
    Stall               = 8,            -- 摆摊
    StoreHot            = 9,            -- 商城-热销
    StoreBeauty         = 10,           -- 商城-装饰
    StoreEngine         = 11,           -- 商城-功能
    StoreFestival       = 12,           -- 商城-节日
    GuildMain           = 13,           -- 行会-主界面
    GuildMember         = 14,           -- 行会成员列表
    GuildList           = 15,           -- 行会列表
    Mail                = 16,           -- 邮件
    Team                = 17,           -- 组队
    NearPlayer          = 18,           -- 附近玩家
    Buff                = 19,           -- 角色-buff/天赋

    MiniMap             = 24,           -- 小地图
    SkillSetting        = 25,           -- 技能设置
    StoreRecharge       = 26,           -- 充值
    Auction             = 27,           -- 拍卖行
    Friend              = 28,           -- 好友
    ExitToRole          = 29,           -- 小退
    GuildCreate         = 30,           -- 行会创建
    Guild               = 31,           -- 智能行会界面
    Rank                = 32,           -- 排行榜
    Trade               = 33,           -- 面对面交易 请求
    ForceExitToRole     = 34,           -- 强制小退
    TradingBank         = 35,           -- 交易行
    GuideEnter          = 36,           -- 引导进入[主界面按钮块显示切换]
    SuperEquip          = 37,           -- 角色-神装
    HeroEquip           = 41,           -- 英雄-装备
    HeroState           = 42,           -- 英雄-状态
    HeroAttri           = 43,           -- 英雄-属性
    HeroSkill           = 44,           -- 英雄-技能
    HeroTitle           = 45,           -- 英雄-称号
    HeroBestRing        = 46,           -- 英雄-首饰盒
    HeroBag             = 47,           -- 英雄-背包
    HeroSuperEquip      = 48,           -- 英雄-神装
    ReinAttrPoint       = 51,           -- 转生属性点
    Chat                = 52,           -- 聊天
    PCPrivate           = 53,           -- PC 私聊记录页

    MagicJointAttack    = 99,           -- 释放合击

    AssistChange        = 110,          -- 主界面-任务栏
    Box996              = 111,          -- 盒子称号
    MainMiniMapChange   = 112,          -- 小地图伸缩
    PCResolution        = 113,          -- PC 分辨率设置
    ChatExtendEmoj      = 114,          -- 角色-表情
    ChatExtendBag       = 115,          -- 聊天小框-背包
    MainNear            = 116,          -- 主界面-附近列表
    CallPay             = 117,          -- 调用-支付

    SettingBasic        = 300,          -- 基础设置
    SettingWindowRange  = 301,          -- 视距
    SettingFight        = 302,          -- 战斗
    SettingProtect      = 303,          -- 保护
    SettingAuto         = 304,          -- 挂机
    SettingHelp         = 305,          -- 帮助
    SettingAutoPick     = 306,          -- 拾取
    
    KeFu                = 310,          -- 调用客服界面
    Community           = 320,          -- 社区帖子
    Compound            = 2201,         -- 合成

                                        -- 人物
    PlayerInternalState     = 401,      -- 内功状态
    PlayerInternalSkill     = 402,      -- 内功技能
    PlayerInternalMeridian  = 403,      -- 内功经络
    PlayerInternalCombo     = 404,      -- 内功连击

                                        -- 英雄
    HeroInternalState       = 501,      -- 内功状态
    HeroInternalSkill       = 502,      -- 内功技能
    HeroInternalMeridian    = 503,      -- 内功经络
    HeroInternalCombo       = 504,      -- 内功连击

    ReviewGift              = 311,      -- 好评有礼

    Purchase                = 601,      -- 求购

    ManualService996 		= 701, 	-- 996客服
}

-- BUFF ID
SLDefine.BUFFID = {
	POISONING_GREEN           = 0,            -- 绿毒
	POISONING_RED             = 1,            -- 红毒
	FREEZED_GRAY              = 5,            -- 麻痹
	CLOAKING                  = 8,            -- 隐身
	ANGEL_SHIELD              = 9,            -- 神圣战甲术
	GHOST_SHIELD              = 10,           -- 幽灵盾
	MAGIC_SHIELD              = 11,           -- 魔法盾
	STONE_MODE                = 12,           -- 石化状态(怪物)
	COBWEB                    = 13,           -- 蛛网
	THUNDER_SWORD             = 21,           -- 雷霆剑法
	ONDASH_IDLE               = 69,           -- 锁定 被野蛮
	UN_IMPRISON               = 70,           -- 防禁锢
	UN_ATTACK                 = 71,           -- 禁止攻击
	SNEAK 					  = 80, 		  -- 潜行
	WUJI_SHIELD               = 1050,         -- 无极真气
	ICE                       = 1113,         -- 冰冻
	COLORS                    = 1123,         -- 变色
	COLOR                     = 2021,         -- 人物变色
	POISON_TRANSPARENT        = 2022,         -- 放大透明虚影
	HORSE 					  = 9999, 	  	  -- 骑马
}

-- spineAnim事件类型
SLDefine.SpineAnimEventType = {
    Start       = 0,
    Interrupt   = 1,
    End         = 2,
    Complete    = 3,
    Dispose     = 4,
    Event       = 5
}